### ISSUE TITLE
Prevent reuse of token

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/twofactor_totp#100]
Ref https://github.com/mdp/rotp/issues/44 – just filing so we don't get any HackerOne tickets about this. Rather minor severity for me.

**Comment by r2evans** [comment]
Broken link ... https://github.com/mdp/rotp/issues/44?

**Comment by wYhyzByH** [comment]
Hi LukasReschke
When the reusage of the TTOP is possible it is of no security use as a MITM attack or keylogger would allow to generate a successful login with full admin rights :-(
So for me the security is not enhanced by much when using this feature as long as this bug is not fixed.
Can you change the priority to **high/critical**, please. This is a severe design issue in the TTOP implementation.

**Comment by LukasReschke** [comment]
> When the reusage of the TTOP is possible it is of no security use as a MITM attack or keylogger would allow to generate a successful login with full admin rights :-(

A malicious application on your device or a MITM attack could also just intercept the cookie 😉

**Comment by wYhyzByH** [comment]
> A malicious application on your device or a successful MITM attack could also just intercept the cookie 

Yes, a MITM would potentially get access to the cookie. But at least it is invalidated as soon as I logout. Another authenticated session could last until next upgrade or reboot.
A keylogger unfortunately does not need direct access, it can be the person behind you, a camera, or a radio listening on the wireless keyboard signals, acoustic analysis...

**Comment by sindastra** [comment]
This still needs fixing. See #245 for my take on it.

This extension is about security after all.

**Comment by ChristophWurst** [comment]
> This still needs fixing.

Who said it was fixed? ;)

**Comment by sindastra** [comment]
See #245 for additional info.

**Comment by sindastra** [comment]
@ChristophWurst That's what #245 was for. It was working fine there until you closed it. Perhaps open it again? Otherwise we'd have 3 tickets with the same issue already.

**Comment by ChristophWurst** [comment]
#245 it is.
