### ISSUE TITLE
Theming does not apply to submit button

### ISSUE THREAD

**Issue by Signum** [nextcloud/twofactor_totp#1006]
### Steps to reproduce
1. Change the background color to #000000 in Admin -> Theming
2. Login using a TOTP-enabled user
3. Look at the color of the submit button

![grafik](https://user-images.githubusercontent.com/36562/101025586-13d3e900-3576-11eb-8df0-68f221749759.png)

### Expected behaviour

Have the submit shown with a black background.

### Actual behaviour

The button has a blue background.

### Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.3.19

**Version:** 19.0.5

**Updated from an older version or fresh install:** Updated.

**List of activated apps:** 

Accessibility
Activity
Brute-force settings
Collaborative tags
Comments
Contacts Interaction
Deleted files
Draw.io
Federation
File sharing
First run wizard
Group folders
Guests
Impersonate
LDAP user and group backend
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
PDF viewer
Photos
Privacy
Recommendations
Right click
Share by mail
Support
Text
Theming
Two-Factor Gateway
Two-Factor TOTP Provider
Two-Factor U2F
Update notification
Usage survey
Versions
Video player

#### Client configuration
**Browser:** Tried on Firefox and Vivaldi/Chrome

**Operating system:** Linux Mint

**Comment by ChristophWurst** [comment]
This rings a bell. I think we fixed this at least once. Could you check the closed ticket for related bug reports? Then we can check if that fix was accidentally reverted.

**Comment by Signum** [comment]
I think you refer to https://github.com/nextcloud/server/issues/14317 which was meant to be fixed by https://github.com/nextcloud/server/pull/21988

**Comment by ChristophWurst** [comment]
Ah yes, that are the ones I was looking for :)

I just noticed that your screenshot shows the backup codes screen. That is part of Nextcloud server. But https://github.com/nextcloud/server/pull/22427 should have fixed this. Maybe the backup codes use the wrong classes or structure.

**Comment by Signum** [comment]
I see. But it also happens when the TOTP code is entered:
![grafik](https://user-images.githubusercontent.com/36562/101062882-73d88880-3592-11eb-9735-8d73cc4c990a.png)

Does that concern the twofactor_totp app?

**Comment by ChristophWurst** [comment]
yep, totally. then it's a regression.

**Comment by ChristophWurst** [comment]
Would you be interesting in learning more about how to debug/fix this? I'm afraid won't find much time to look into this the next few weeks.

**Comment by Signum** [comment]
To be honest I'm not a PHP guy. And I'm stuck in a few other projects. Just thought I'd report it anyway. Please bear with me. :)

For those looking for a workaround:

* install the "custom CSS" app (from the "Customisation" category)
* use this snippet in "Admin" -> "Theming" to set the background of the button
```
button.two-factor-submit { background-color: black };
```

**Comment by ChristophWurst** [comment]
No worries. Appreciate the time you took to report this and thanks for the tip for others :v:

**Comment by newhinton** [comment]
@Signum Does the workaround still work for you? In my nc-23 instance the customcss api endpoint is redirected to
`/login/selectchallenge?redirect_url=/apps/theming_customcss/styles` which completely breaks this.

**Comment by skjnldsv** [comment]
Should be fixed on nc25

**Comment by newhinton** [comment]
> Should be fixed on nc25

So this issue is in the server and the loading will "just work" again with 25? Thats good news. 
On the other hand, is there a known workaround for 23 and 24?

**Comment by skjnldsv** [comment]
![image](https://user-images.githubusercontent.com/14975046/170742005-b6bf49f1-5504-47fb-8f58-e3fb84250c0d.png)
