### ISSUE TITLE
[App-Passwords section] I don't see application or device names, and also cannot edit them

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/twofactor_totp#101]
![20161213-18 54 14_auswahl](https://cloud.githubusercontent.com/assets/1151915/21152287/f00ca4a4-c165-11e6-8a30-411dd67084a4.png)

**Comment by Wikinaut** [comment]
also interesting would be the time of the initial addition, and perhaps the IP number, of the specific device. Currently, only the last access is shown.

**Comment by Wikinaut** [comment]
My devices / apps are:

* Mac OS Owncloud client
* Android Nextcloud client
* debian 8 owncloud clien

**Comment by Wikinaut** [comment]
Ah, now I understand, I have to enter a name **before** I add a device specific password.

**Comment by LukasReschke** [comment]
cc @jancborchardt For UX

**Comment by Wikinaut** [comment]
@LukasReschke Shall I open a new issue (suggestions) ?

**Comment by jancborchardt** [comment]
@LukasReschke @ChristophWurst it should be possible to add/edit app names for existing app passwords, right? That would take care of this issue.

**Comment by Wikinaut** [comment]
:+1:
