### ISSUE TITLE
[11.0.0] cannot enable twofactor_totp

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/twofactor_totp#102]
Message:

After upgrading to Nextcloud 11.0.0:

```
App "Two Factor TOTP Provider" cannot be installed
because the following dependencies are not fulfilled: Server version 9.2 or lower is required.
```

???

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/twofactor_totp/issues/95
!!!

**Comment by Wikinaut** [comment]
Reason was: /nextcloud/apps/twofactor_totp had root:root ownerships instead of www-data:www-data.
After fixing the ownership, deinstallation and installation worked fine.

**Comment by sycophantic** [comment]
I upgraded from 10 to 11 and had the same issue, but the cause was an old copy the of totp app.  Deleted it (via shell) and reinstalled via the app page.
