### ISSUE TITLE
Two factor TOTP Not working

### ISSUE THREAD

**Issue by JAGX13** [nextcloud/twofactor_totp#1023]
### Steps to reproduce
1. Attempt login with TOTP codes various accounts, not working
2. Attempt to create new TOTP for account, passkey provided, once returning a key it says not verified
3.

### Expected behaviour
Tell us what should happen
Login with 2FA via TOTP

### Actual behaviour
Tell us what happens instead
Complete failure of TOTP Nextcloud 19.06, remove and set up again fails.

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by ChristophWurst** [comment]
Screenshots? Logs?

**Comment by JAGX13** [comment]
Issue resolved, was an issue NTP time sync issue on my host. Stopping and restating it has resolved the problem.
