### ISSUE TITLE
NC11.0.0: Printing backup codes fails

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/twofactor_totp#103]
One page is printed, but this is only covering the upper left part of the whole browser window (section "Persönlich" and start of the Profile), but not the codes.

**Comment by Wikinaut** [comment]
but see also https://github.com/nextcloud/twofactor_totp/issues/102 (the twofactor_totp app could not be installed yet).

**Comment by ChristophWurst** [comment]
Please file an issue at https://github.com/nextcloud/server/issues/new :-)
