### ISSUE TITLE
2FA code not accepted

### ISSUE THREAD

**Issue by Gaetan25** [nextcloud/twofactor_totp#105]
Hello,

I've just activated the app into my nextcloud v11 but when I try to log in my 2FA code generated through the Authy application is not accepted. I tried multiple token length (6, 7 or 8) without any success.

Can you help ?

**Comment by ChristophWurst** [comment]
Hi,

1. compare your server's and your phone's clock. They should be in sync, the maximum time drift is about 30secs.
2. if there's anything in the Nextcloud log, please post it here

Thanks.

**Comment by Gaetan25** [comment]
Hi,

the TOTP works fine on other application managed by the same 

I have the following error log:
Error	PHP	Undefined index: redirect_url at ***/core/templates/twofactorshowchallenge.php#24

**Comment by ChristophWurst** [comment]
> the TOTP works fine on other application managed by the same

Did you compare the time on your phone with the one on your server? Maybe the server you NC installation is running on has a time drift.

**Comment by ChristophWurst** [comment]
> I have the following error log:
> Error PHP Undefined index: redirect_url at ***/core/templates/twofactorshowchallenge.php#24

That's a known bug, but unrelated: https://github.com/nextcloud/server/issues/2376

**Comment by ChristophWurst** [comment]
> Did you compare the time on your phone with the one on your server? Maybe the server you NC installation is running on has a time drift.

Ping 😉 Any results? Does it work now?

**Comment by cedjo** [comment]
I had the same problem, token & server time had 7 minutes difference...
Activated ntp on the server and problem is solved.

Thanks

**Comment by ChristophWurst** [comment]
Great!
