### ISSUE TITLE
NextCloud 20.0.5

### ISSUE THREAD

**Issue by fzonno** [nextcloud/twofactor_totp#1051]
### Steps to reproduce
1. Upgrade NextCloud from 20.0.4 to 20.0.5
2. The App Two-Factor TOTP Provider disappears from Active Apps
3. The App Two-Factor TOTP Provider disappears from the App Store inside the appliance

### Actual behaviour
Unable to use the Two-Factor Authentication, the only way to logon is backup code

### Server configuration

**Operating system**:
Ubuntu 18.04.5 LTS

**Web server:**
Apache
**Database:**

**PHP version:**

**Version:** (see admin page)
The official Nextcloud VM is made by T&M Hansson IT AB 20.0.4

**Updated from an older version or fresh install:**
Updated

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - extract: 1.3.0
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - issuetemplate: 0.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - mail

**The content of config/config.php:**
```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "10.0.1.8",
            "nextcloud.3puntozero.eu",
            "nextcloud.3puntozero.eu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.4.0",
        "overwrite.cli.url": "https:\/\/nextcloud.3puntozero.eu\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto, 365",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "PLAIN",
        "theme": "",
        "loglevel": "2",
        "app_install_overwrite": [
            "extract"
        ],
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin",
            "Tecnico"
        ],
        "twofactor_enforced_excluded_groups": []
    }
}

```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by gewaaid** [comment]
Same after fresh install 20.0.5. TOTP not available in app store.

**Comment by rovert9888** [comment]
Same here. I even tried downloading the latest twofactor release and putting it in the apps folder. Still doesn't show up

**Comment by ChristophWurst** [comment]
> PHP version:

so … ?

**Comment by gewaaid** [comment]
PHP 7.2.24
Server Ubuntu 18.04.5

**Comment by johanfleury** [comment]
So I faced the same issue on Debian 10 (Buster) with PHP 7.3.

I doubt this is an environment issue as installing the application from the tar.gz file and enabling it via `occ` works fine.

```
$ wget https://github.com/nextcloud/twofactor_totp/releases/download/v5.0.0/twofactor_totp.tar.gz
$ tar -xf twofactor_totp.tar.gz
$ mv twofactor_totp /<your nextcloud direcotry>/apps/
$ occ app:enable twofactor_totp # See the official documentation on how to run occ in your environment: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html
```

**Comment by rovert9888** [comment]
> So I faced the same issue on Debian 10 (Buster) with PHP 7.3.
> 
> I doubt this is an environment issue as installing the application from the tar.gz file and enabling it via `occ` works fine.
> 
> ```
> $ wget https://github.com/nextcloud/twofactor_totp/releases/download/v5.0.0/twofactor_totp.tar.gz
> $ tar -xf twofactor_totp.tar.gz
> $ mv twofactor_totp /<your nextcloud direcotry>/apps/
> $ occ app:enable twofactor_totp # See the official documentation on how to run occ in your environment: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html
> ```

Followed your steps for occ and it enabled it in my environment. I'm running php 7.3 on Ubuntu 18.04

**Comment by micredd** [comment]
Likely a result of issue [#773982](https://github.com/nextcloud/server/issues/25137) in Nextcloud Server. TOTP stopped working on my Nextcloud instance upon upgrading to NC 20.0.5 and I also began noticing a huge spike in the size of my Nextcloud logs. Tracked it down to the above issue and changed lines 116 and 121 of AppFetcher.php per the [associated pull request](https://github.com/nextcloud/server/pull/25138) (which indicates that the issue affects this app).

We'll see if this lets me reinstall this app in time.

**Comment by gewaaid** [comment]
I also can confirm that after adjusting AppFetcher.php, lines 116 and 121. I was able to find and install the TOTP app.

**Comment by iGadget** [comment]
> Tracked it down to the above issue and changed lines 116 and 121 of AppFetcher.php per the [associated pull request](https://github.com/nextcloud/server/pull/25138) (which indicates that the issue affects this app).
Confirmed. Changing these 2 lines made the missing apps show up again in the app store.
For those wondering where to find AppFetcher.php - it's located (at least on my system) in
`/var/www/nextcloud/lib/private/App/AppStore/Fetcher`

**Comment by kesselb** [comment]
Closing the report in favour of https://github.com/nextcloud/server/issues/25137.

**Comment by arneboeses** [comment]
just installed 20.0.5 yesterday via latest.zip package and also upgraded via web this morning to 20.0.6 but app is still not there
