### ISSUE TITLE
TOTP not avail in APP section Running NC 20.0.6

### ISSUE THREAD

**Issue by dzidasecurities** [nextcloud/twofactor_totp#1065]
I am running Ubuntu 18.04.5LTS  and Rancher 2.5.5 in installed Nextcloud 20.0.6 but the TOTP app is not available in the APPS section.
I ran Ubuntu "upgrade" for all patches and and updates on this version of the OS and Rancher and NC seem to be the latest.
Did something happen in the last 3 days that changed with NC, because, I did the same install 1 day prior on the same OS and TOTP was available and I got it working. I had to start over because I only gave the Ubuntu 40 GB of disk space (on VMware esxi 6.7U3) and I could NOT increase the disk space (ESXi grayed out the box), gpart did not work because it could not see any new space because esxi would not allow it.
ANYHOW, I want to use TOTP but its not even showing up.... how to fix this?

**Comment by ChristophWurst** [comment]
Known and fixed https://github.com/nextcloud/server/pull/25335
