### ISSUE TITLE
App not visible nor installable in NC 20.0.5

### ISSUE THREAD

**Issue by eqipe-leon** [nextcloud/twofactor_totp#1066]
### Steps to reproduce
1. Opened "Apps"
2. Searched for "totp"
3. No Apps are showing

### Expected behaviour
App should be able to be installed in NC 20.0.5.

### Actual behaviour
The app isn't shown when searched for.

It would be interesting to know if others have the same issue. We just tested it in a newly installed NC 20.0.5 instance. In NC 20.0.6 this seems to be fixed.

**Comment by fabioleite0** [comment]
Same here after a fresh installation of NC 20.0.6

**Comment by jonasgarstick** [comment]
Also via command line occ app:install twofactor_totp you get:
Error: Could not download app twofactor_totp

**Comment by ChristophWurst** [comment]
Known and fixed https://github.com/nextcloud/server/pull/25335
