### ISSUE TITLE
twofactor_totp reset on upgrade from Nextcloud 20.05 to 20.06

### ISSUE THREAD

**Issue by zardoz047** [nextcloud/twofactor_totp#1067]
I just upgraded my NextCloud from 20.05 to 20.06.  When I tried to login I got a message saying 2FA was enabled, but not setup so I should use a backup code.  Since I was not certain if there are other issues with version 20.06, I just replaced 20.06 with 20.05.

This is just a notification of a possible issue, but may not be an issue with the 2FA app.  No need to act on this now as I rolled back my install to 20.05 and 2FA is working fine.

**Comment by ChristophWurst** [comment]
I don't think it was reset. Sounds more like the app got disabled.

Please use https://help.nextcloud.com/c/apps/twofactor-totp/47 for support topics.
