### ISSUE TITLE
Improve the backup code print page layout: add info header with basic server information, and time/date stamp

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/twofactor_totp#107]
The present backup code print page shows only codes. 

#### Suggestion 

* add an information header for what the codes are (Server name, or at least the general cloud name) and current timestamp.

**Comment by GoetheG** [comment]
Yes @Wikinaut, this would be a great function. Agree.

**Comment by ChristophWurst** [comment]
Backup codes are independent of this app and part of the [server](https://github.com/nextcloud/server) code. Please file issues there. Pull requests to improve this feature are very welcome!
