### ISSUE TITLE
No app update available for 20.0.7

### ISSUE THREAD

**Issue by eibex** [nextcloud/twofactor_totp#1073]
Hello,

NC 20.0.7 is now available for my instance but this app shows it has no updates available for 20.0.7 even though in the app store the current release supports up to NC 21. 

Is this a known bug and can the server be updated without being locked out of it?

**Comment by ChristophWurst** [comment]
did you just update? There was bug in 20.0.6 that hid the app from the app store (wrongly considered incompatible) but once the cached expired and nextcloud will refresh the list of apps, you should see the release. Please check again in a few hours!

**Comment by eibex** [comment]
I updated to 20.0.6 quite a bit ago now and haven't noticed that bug. I will check again in a few hours.

**Comment by poltrian** [comment]
Same here, 20.0.6 was fine and 20.0.7 are Music, Mail and the TOPT app not compatible. So i will wait as Christoph says.

**Comment by Findus23** [comment]
I ignored the message and still updated from 20.0.6 to 20.0.7 and the plugin is still working and enabled (as expected). So I guess it is indeed just the compatibility check in 20.0.6 that doesn't work.

**Comment by eibex** [comment]
> I ignored the message and still updated from 20.0.6 to 20.0.7 and the plugin is still working and enabled (as expected). So I guess it is indeed just the compatibility check in 20.0.6 that doesn't work.

Thanks for the heads up. I was starting to think that was the issue too since it happened between NC 19 > 20.

I went ahead and tried it out as I backed up the DB etc. and all apps are still working as expected.

**Comment by ChristophWurst** [comment]
right … we are very likely using the same check for the update compatibility note … whooooopsie …

https://github.com/nextcloud/server/pull/25335 was the fix FYI and there are some instructions for how to patch 20.0.6 if anyone needs that. otherwise just to go .7 and you'll be fine :)

**Comment by poltrian** [comment]
I can confirm, no problems after update to 20.0.7
