### ISSUE TITLE
No update available for Nextcloud 20.0.7

### ISSUE THREAD

**Issue by brot** [nextcloud/twofactor_totp#1074]
Will there be an update for the latest released version 20.0.7?

Nextcloud shows me that this App is not compatible with the latest version
![image](https://user-images.githubusercontent.com/36720/106863944-87ef5200-66c9-11eb-97f4-95936c9bb284.png)

**Comment by tlinna** [comment]
Duplicate of #1073

**Comment by ChristophWurst** [comment]
yeah … just ignore the warning one time :)

**Comment by brianWreaves** [comment]
I presume it's also ok to update to 20.0.8?
