### ISSUE TITLE
Option to trust PC for specified time period

### ISSUE THREAD

**Issue by wallenium** [nextcloud/twofactor_totp#108]
2FA working great, but could be improved for better acceptance of users. Currently, the code is required on every Login.

**Suggestion**
It would be great to have an Option, to trust a Computer for a defined period of time (30 days would be great). During this time Frame, the Code does not Need to be entered while logging in. This would improve the handling a lot.

Security wise should it be OK, for sure it it less secure than adding the code on each Login process, but most users will not enable it if you require it on each Login process.

**Comment by ChristophWurst** [comment]
Hi,

this would be a great enhancement and also other 2FA providers should support it. Therefore, I suggest to raise a ticket in the server repo because we have to implement that there instead of this specific provider. This app does not have control over the 2FA workflow.

**Comment by wallenium** [comment]
Opened a fewture request: https://github.com/nextcloud/server/issues/2906
