### ISSUE TITLE
Two OTP entries in authenticator app no longer possible?

### ISSUE THREAD

**Issue by RB72** [nextcloud/twofactor_totp#1096]
### Steps to reproduce
1. Enable TOTP for Administrator account on phone authenticator
2. Create new user
3. Enable TOTP for new user on same phone authenticator

### Expected behaviour
I expected to have two entries on my phone app, one for the administrator account (me) and one for the new user account (also me). This was the behavior of earlier versions of NC with this app.

### Actual behaviour
The administrator entry is replaced with the entry for the new user. So I can only add one account to my phone authenticator.

### Server configuration

**Operating system:**
Debian 10.9

**Web server:**
Nginx 1.19.10

**Database:**
Mysql 10.5.9

**PHP version:**
8.0.3

**Version:** (see admin page)
21.0.1

**Updated from an older version or fresh install:**
Fresh install

**List of activated apps:**
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - bruteforcesettings: 2.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_antivirus: 3.2.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_nextcloud_notification: 3.1.2
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0

**Comment by ChristophWurst** [comment]
I'd say try with another mobile app. We are not forcing this. If your app deduplicates and overrides the older registration then we can't do anything about it.

**Comment by RB72** [comment]
Ok, thanks, I am going to test that.
I will report back the results.

**Comment by RB72** [comment]
Thank you, another authenticator app seems to do the job. Problem solved!
