### ISSUE TITLE
Remove google from "TOTP (Google Authenticator)"

### ISSUE THREAD

**Issue by tflidd** [nextcloud/twofactor_totp#110]
### Steps to reproduce
1. Setup TOTP 2FA (e.g. yubikey)
2. Login with username & password
3. screen shows `TOTP (Google Authenticator)`

### Expected solution
Either specify the actual used method or just use something generic such as `TOTP-Authentication`. Like this it confuses people who don't use the google thing.

**Comment by ChristophWurst** [comment]
Hi,

I don't like the "Google" either but unfortunately this authentication technique is widely known becaus of the google authenticator app. Only a minority (of geeks) knows what "TOTP" or "RFC 6238" stands is. What do other platforms call it? How is it labeled there?

**Comment by tflidd** [comment]
You could use just TOTP (or the actual words) in the personal settings and then put in brackets (e.g. `Google Authenticator`, `Yubikey Authenticator`, ...) and during login only TOTP or one time password.

On my setup I did some first tests with google authenticator but switched to yubikey later. I was really confused when it asked to put my google authenticator key and it didn't work. I wasn't even sure if it worked with solutions other than google authenticator (at least the app name was changed).

**Comment by Yomark1** [comment]
It's not like normal users know what google authenticator is either, so it's only confusing. 
I enabled it here at our organization, and people though that they had to put in their Google password, even when they just installed an OTP app on their telephone and scanned the barcode. 

Better would be "One Time Password" or "Second factor authentication code". In our case with our users, "The code from that OTP app thingy on your smartphone"

**Comment by Celti** [comment]
I too find “Google Authenticator” jarring when I don't actually use Google Authenticator for TOTP. All the various clients out there use some variant of “X Authenticator”, with the open-source fork of the last open Google Authenticator version being simply called “Authenticator” — thus, I think a name of something like “TOTP (Authenticator)” would be appropriate and sufficient.

**Comment by r2evans** [comment]
I second @Yomark1's suggestion to call it "one time password" or "second factor authentication". You can include "TOTP" and/or "2FA" parenthetically if desired, since those both have clear and non-branded associations.

**Comment by ChristophWurst** [comment]
How about "Authenticator app". That's what Google and Microsoft call it on their platforms. IMO the term is simple, clear and vendor neutral.

**Comment by Yomark1** [comment]
Yes, that'll do nicely I think.
