### ISSUE TITLE
Tested with Authy on iOS 14!

### ISSUE THREAD

**Issue by rainy-goose** [nextcloud/twofactor_totp#1132]
Tested this app on my iPhone 11 with iOS 14 using Authy, worked totally fine!

**Comment by ChristophWurst** [comment]
Awesome! You may shoot a pull request to update the list in the readme :)

**Comment by dflvunoooooo** [comment]
Does also work with Authy on Android.

**Comment by ChristophWurst** [comment]
Great! Feel free to open a pull request that adds this to the list of tested applications

**Comment by dflvunoooooo** [comment]
I would love to, but I have never done that. Can you tell me to which version I should compare the change to?

**Comment by ChristophWurst** [comment]
You can do the change based on latest master. https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests will help you get started with Github.

**Comment by dflvunoooooo** [comment]
Thank you very much. I opened a pull request, hope it was the correct way.
