### ISSUE TITLE
Fail2ban ubuntu

### ISSUE THREAD

**Issue by Bergum** [nextcloud/twofactor_totp#1143]
### Steps to reproduce
1. install fail2ban, activate it, add roules for SSH, http, and https.
2. log into nextcloud.
3. enter user/pass, press enter, and the circle starts spinning, no totp prompt is displayed
4. disable fail2ban, log in as usual

### Expected behaviour
log into wordpress with user/pass, use totp at prompt, log inn.

### Actual behaviour
log into wordpress with user/pass, No totp prompt is displayed, the circle at login is spinning

### Server configuration

**Operating system**: Ubuntu 18

**Web server:** Apache2

**Database:** MySql

**PHP version:** 7.4

**Version:** (see admin page) 21.0.4

**Updated from an older version or fresh install:** Updated

**List of activated apps:**
  - accessibility: 1.7.0
  - activity: 2.15.0
  - admin_audit: 1.11.0
  - apporder: 0.13.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.2
  - circles: 22.1.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.2
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - extract: 1.3.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.9
  - nextbackup: 21.1.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - onlyoffice: 7.1.2
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - viewer: 1.6.0
  - workflowengine: 2.3.1

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "grey.bbergum.no"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.1.1.2",
        "overwrite.cli.url": "https:\/\/grey.bbergum.no",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "NO",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "onlyoffice",
            "maps",
            "documentserver_community",
            "contacts",
            "social",
            "printer",
            "apporder",
            "bruteforcesettings",
            "nextbackup",
            "twofactor_totp",
            "extract"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:**
crome
**Operating system:**

##### Web server error log
[Tue Sep 21 00:06:59.033025 2021] [mpm_prefork:notice] [pid 1031] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Sep 21 00:06:59.033048 2021] [core:notice] [pid 1031] AH00094: Command line: '/usr/sbin/apache2'

```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

{"reqId":"sLpA7rQmzCSdoM5ijOP6","level":3,"time":"2020-03-03T16:04:39+00:00","remoteAddr":"192.168.1.26","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/Setup.php#312","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36","version":""}
{"reqId":"ynZbLxZHhHgTSqLiVxhg","level":3,"time":"2020-03-03T16:08:39+00:00","remoteAddr":"192.168.1.26","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/Setup.php#312","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36","version":""}
{"reqId":"sA3j12gVAPhAgM2pyvSE","level":3,"time":"2020-03-03T16:36:44+00:00","remoteAddr":"192.168.1.26","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/Setup.php#312","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36","version":""}
{"reqId":"KoakzPmZxd58MiJPIPge","level":3,"time":"2020-03-03T16:41:49+00:00","remoteAddr":"192.168.1.26","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/Setup.php#312","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36","version":""}
{"reqId":"w8HOtNBLMVm6rqVZSizk","level":3,"time":"2020-03-03T16:45:27+00:00","remoteAddr":"192.168.1.26","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/Setup.php#312","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36","version":""}
{"reqId":"QtLwEm9nFiTwbML5HM8C","level":3,"time":"2020-03-03T16:56:56+00:00","remoteAddr":"192.168.1.26","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/Setup.php#312","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36","version":""}

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by ChristophWurst** [comment]
this is the issue tracker of totp for *Nextcloud*, not wordpress.

**Comment by Bergum** [comment]
But, this is nextcloud, not wordpress....

**Comment by ChristophWurst** [comment]
> log into wordpress with user/pass

is it?

**Comment by ChristophWurst** [comment]
> ### Actual behaviour
> 
> log into nextcloud with user/pass, No totp prompt is displayed, the circle at login is spinning

I'm sorry but I'm not able to follow your description. Could you try to rephrase? Can you add screenshots? TOTP always happens *after* login+password.

I have no idea how your fail2bin hooks into Nextcloud. You might want to report this wherever you found the instructions for fail2ban with Nextcloud.

**Comment by Bergum** [comment]
@ChristophWurst 
I have used nextcloud and totp for a long time, but i wanted to up the game by installing fail2ban.
I hav not enabled anything else than just fail2ban and enabled http and https and ssh.
I still can reatch the nextcloud loging page, and start the loging prosess, bur with fail2ban enabled on the system, i cant get to the totp prompt.

So, no guide has been followed.

**Comment by Bergum** [comment]
@ChristophWurs
![login](https://user-images.githubusercontent.com/4532499/134177606-7abd787e-f1a9-4ab1-adcf-7ea5a1eb1070.jpg)
![Login-Next](https://user-images.githubusercontent.com/4532499/134177610-5fb7510e-c951-40fb-bae5-3d1016a24bfc.jpg)
t

**Comment by ChristophWurst** [comment]
> I still can reatch the nextcloud loging page, and start the loging prosess, bur with fail2ban enabled on the system, i cant get to the totp prompt.

do you enter the correct or incorrect username+password? Nextcloud brute force protection might just slow down the process.

There is nothing we can really do in the scope of twofactor_totp.It doesn't block anything. Nor does it have influence on what fail2ban does. If the default fail2ban setup doesn't do what you expect than you have to tweak it.

**Comment by Bergum** [comment]
@ChristophWurst 
I have to see if i can find anything.
Thank you for the reply :-)

**Comment by Bergum** [comment]
Note to self and others.
Follow the guide, if you dont have a guide, find one...
