### ISSUE TITLE
Undefined index Error at Logging in

### ISSUE THREAD

**Issue by Vespa-Ferox** [nextcloud/twofactor_totp#115]
Salve!
Every time a TOTP User logs in there comes the following error msg, but logging in still works

`Error	PHP	Undefined index: redirect_url at /nextcloud/core/templates/twofactorshowchallenge.php#24`

**Comment by ChristophWurst** [comment]
Hi,

this was fixed in the Nextcloud server in https://github.com/nextcloud/server/pull/2854.
