### ISSUE TITLE
occ twofactorauth:cleanup totp manually instead after gui removal of group subject of totp

### ISSUE THREAD

**Issue by MrEcrm** [nextcloud/twofactor_totp#1152]
### Steps to reproduce
1.Settings
security
Enable totp
enforce two-factor authentication

2 groups ticked.

The user of this group did have 2 way enforced

Settings
security
Enable totp
enforce two-factor authentication

1 group UN-ticked.
1 group ticked

The user of the un-ticked group did still have 2 way enforced

Settings
security
Enable totp
enforce two-factor authentication UN-Ticked save changes

The user of the un-ticked group did still have 2 way enforced

Settings
security
Enable totp
enforce two-factor authentication

this one group added  to excluded groups, having other ticked.

The user of this group did still have 2 way enforced

Settings
apps
Two-Factor TOTP provider disabled

no longer entered into the system:

Two-factor authentication Could not load at least one of your enabled two-factor auth methods. Please contact your admin. Two-factor authentication is enforced but has not been configured on your account. Contact your admin for assistance.
0r of this group did still have 2 way enforced

admin locked out :-(

2.
3.

### Expected behaviour
Tell us what should happen
once a group is unticked, the users of the group would no longer be subject of 2way auth.
if i would add this unticked group additionally to the excluded group, the users subject of the unticked and excluded group would no longer be subject of the two way auth

### Actual behaviour
Tell us what happens instead
independently of my group manipulation, the users of the group remained subject of the to way auth.
btw: the config.php twofactor_enforced was not set to true and arrays of enforced or excluded groups were correct (/var/www/nextcloud/config/nano config.php)
rebooted the server after each manipulation init6

### Server configuration

**Operating system**: debian bullseye 11

**Web server:**

**Database:**

**PHP version:**7.4.25

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```
workaround for me was to solve the issue manually by running:

solution: 
/var/www/nextcloud/config# sudo -u www-data php occ twofactorauth:state username 
told me that the user was still subject of two way auth even though he was exclusively in a group that was not ticked for 2way auth but ticked for excluded 2way auth (double ...)

what did the job:
sudo -u www-data php /var/www/nextcloud/occ twofactorauth:cleanup totp

**Comment by MrEcrm** [comment]
hmm I was too optimistic it did not resolve my issue but no I can log in as an admin again to the cloud UI at last.
but the users which were part of a group subject of 2 way auth and no longer should have 2 way auth required get still the 2 way screen prompted...  
and yes, deactivation of the app might make things rather worse than just turn all off... :-( (somehow 2 way would still be active and required even though the 2 way app has been turned off so to say.)

**Comment by ChristophWurst** [comment]
If two factor authentication is no longer enforced but the users configured it then it will still be checked. This is intended. Only if the users didn't set it up and you drop the enforcement it will be off.

In other words, removing enforced 2FA does not imply disabling 2FA.
