### ISSUE TITLE
2FA from LAN disabled, from WAN/Internet enabled

### ISSUE THREAD

**Issue by Koky999** [nextcloud/twofactor_totp#1162]
### Feature Request

Is possible to add some settings, which controle if 2FA is needed when log in or nor? When I am in the office, on LAN, I don't want to login with 2FA, but when I log in from home, over the Internet, I must use 2FA.

Thank you very much.

**Comment by luckym-boop** [comment]
I support this idea. This is a very useful feature.

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/server/issues/2035

**Comment by Koky999** [comment]
Okay, didn't find this, thanks.
