### ISSUE TITLE
Nextcloud Update 23.0.0 Supported?

### ISSUE THREAD

**Issue by TheSamDickey** [nextcloud/twofactor_totp#1168]
Hello,

I just updated Nextcloud to version 23.0.0, and am wondering if it is safe to enable TOTP?

To enable it, I would have to click the red 'enable untested application' button.  I'm not sure if that button is risky or not.

Does anyone know if I should wait?  Or have you had any luck with it?

**Comment by ChristophWurst** [comment]
Use v6.2 https://apps.nextcloud.com/apps/twofactor_totp does the app store not offer it for you?
