### ISSUE TITLE
Problems Updating

### ISSUE THREAD

**Issue by adamlove86** [nextcloud/twofactor_totp#118]
Hi there, I've upgraded to nextcloud snap 11, and can't seem to get it to upgrade the app. I'm constantly getting the "you have 1 app update pending" message.
When I go to update it in the web interface by clicking the update button, it says it's updating and installed, however when I click to another page it goes back to saying it needs updating. I've tried doing it via maintenance mode, and deleting and downloading the whole thing again from git into the "extra-apps" folder, but still have the same problem.
Any other info you need, let me know.

**Comment by ChristophWurst** [comment]
Can you somehow provide steps to reproduce this bug with a fresh install? It's hard to tell where an issue occurs. Could be this app, but could also be the server component.

> downloading the whole thing again from git into the "extra-apps" folder, but still have the same problem.

Generally, that won't work. You'll have missing php dependencies and probably other issues. Please use a release from either the app store or from https://github.com/nextcloud/twofactor_totp/releases

**Comment by adamlove86** [comment]
Hi there, sorry for the delay. I am in this screen, and clicked update. It seems to have worked today.
![screen shot 2017-01-24 at 09 56 07](https://cloud.githubusercontent.com/assets/20361489/22226713/944b3c58-e21b-11e6-8d07-79184d120e63.png)
I now have nextcloud snap 11.01, and it looks like twofactor is now up to version 1.0, so hopefully one of these factors fixed the issue!

**Comment by ChristophWurst** [comment]
Great!
