### ISSUE TITLE
OTP Password Entry Page Refreshes every 3 seconds

### ISSUE THREAD

**Issue by kevdogg** [nextcloud/twofactor_totp#119]
I'm not sure if this is a defect in twofactor or owncloud, however when presented with the totp page, the page refreshes seemingly every 3 seconds making it very difficult to type in the 6 digit passcode particularly on a mobile device.  Can this be changed either with the plugin or on own/nextcloud?

**Comment by ChristophWurst** [comment]
This is a defect of ownCloud, which is not supported anymore.

Works fine with Nextcloud 10, 11 and 12
