### ISSUE TITLE
Cannot enable totp for user after disabling it.

### ISSUE THREAD

**Issue by Pakbon** [nextcloud/twofactor_totp#1217]
### Steps to reproduce
1. ./occ twofactorauth: disable <user> totp
2. ./occ twofactorauth: enable <user> totp
3. "The provider does not support this operation."

### Expected behaviour
I can enable totp at my own discretion

### Actual behaviour
After disabling totp, enabling does not wrk under any circumstances. I keep getting the the error "The provider does not support this operation:

### Server configuration

**Operating system**:
Ubuntu 20.04 LTS

**Web server:**

**Database:**

**PHP version:**
7.4.3
**Version:** (see admin page)
23.03
**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by ChristophWurst** [comment]
An admin can't enable the provider for a user. User presence is required to scan the QR code.
