### ISSUE TITLE
2fa app in Nextcloud 24 apps settings?

### ISSUE THREAD

**Issue by Japhys** [nextcloud/twofactor_totp#1219]
I just did a fresh install of NC 24 on Ubuntu 22.04 / PHP 8.1 / MariaDB

I noticed this app cannot be installed through Nextcloud UI because the app is not listed.

Any idea why not? :)

**Comment by lnx09** [comment]
You can't see the app because PHP with version lower than 8.0 is required. This is the warning when I try to install it manually :

> This app cannot be installed because the following dependencies are not fulfilled:
> PHP with a version lower than 8.0 is required.

**Comment by sebaxakerhtc** [comment]
Same here
PHP8.1
I need this app, but there's no app TOTP in nextcloud app store. 
Also there's no mail app...

**Comment by lnx09** [comment]
> Also there's no mail app...

"Two-Factor Email" is available in the app store. It works for me.

**Comment by Japhys** [comment]
I rather use my yubikey, even if it's TOTP Hopefully it will be updated soon. It's a must have service for a private cloud.

**Comment by sebaxakerhtc** [comment]
> > Also there's no mail app...
> 
> "Two-Factor Email" is available in the app store. It works for me.

For me too. But there are two diferent apps missing: "mail" and "TOTP"

**Comment by xelayz** [comment]
I have the same problem. Hopyfully it will be updated soon. It took me a while to figure out whats going on. After I installed it manually it was not possible to activate it and I got the php error.

**Comment by horiveira** [comment]
I'm also getting this error with a new installation of Nextcloud. 

> This app cannot be installed because the following dependencies are not fulfilled:
> PHP with a version lower than 8.0 is required.

**Comment by Tymose** [comment]
Same issue here. Seems to be connected with PHP 8.1. Any plans to update or should I revert back to PHP 8.0?

**Comment by eugef66** [comment]
@Tymose 
I found a workaround which works for me and makes TOTP available on NC24 on PHP8.1
I downloaded latest version of TOTP from Nextcloud Store https://apps.nextcloud.com/apps/twofactor_totp and unpacked into /apps folder in my Nextcloud working folder (e.g. /var/www/nextcloud/apps/).

Then all i needed to do is open info.xml file (e.g. /var/www/nextcloud/apps/twofactor_totp/appinfo/info.xml) file and change pho max-version to max-version="8.1"

**Comment by xelayz** [comment]
Working great so far, thanks @eugef66

**Comment by Tymose** [comment]
@eugef66 - Thanks a lot - working now.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/twofactor_totp/issues/1192.

**Comment by Japhys** [comment]
I rather use my yubikey, even if it's TOTP Hopefully it will be updated soon.

-------- Oorspronkelijk bericht --------
Op 21 mei 2022 22:09, lnx09 schreef :
