### ISSUE TITLE
Extra Click Required for Login?

### ISSUE THREAD

**Issue by benyanke** [nextcloud/twofactor_totp#122]
Is there any security reason why the user has to click once more before entering the 2nd factor?

If not, I propose it's removal.

![image](https://cloud.githubusercontent.com/assets/4274911/22045554/8e44bdba-dce0-11e6-96cb-1a3e30f9585d.png)

**Comment by ChristophWurst** [comment]
Hey,

which version of Nextcloud is this? We've changed this behavior long time ago, you're now redirected automatically if you have only one provider configured.

**Comment by benyanke** [comment]
10.0.3. The most recent stable version.

**Comment by ChristophWurst** [comment]
11.x is the most recent stable version ;-)

**Comment by ChristophWurst** [comment]
I'm closing this because the reported enhancement has been implemented already.
