### ISSUE TITLE
Submit button has default color, but should use custom color

### ISSUE THREAD

**Issue by hartsberger** [nextcloud/twofactor_totp#1232]
### Steps to reproduce
1. Try to login and choose TOTP
2. The button below the one time code textfield shows the default NC blue. 
3. (If you hover over the button, it shows the custom color, defined in our instance. )

Blue button: 

![2022-06-14 14_21_31-Window](https://user-images.githubusercontent.com/60740965/173576261-06ca5182-6040-4615-b515-cb899be871c1.png)

Custom color button: 

![2022-06-14 14_22_42-Window](https://user-images.githubusercontent.com/60740965/173576255-1c0835c1-dd1b-4424-8359-56d687487608.png)

Seems like the guest.css is overwriting the custom color in this case. 
I am not sure if this has to do with the guests app (enabled). 

### Expected behaviour
Show the button in the custom color. 

### Actual behaviour
Shows NC default blue as color. 

### Server configuration

**Operating system**:

**Web server:**

**Database:**
PostgreSQL 12.11
**PHP version:**
7.4.3
**Version:** (see admin page)
21.0.9.5

**Updated from an older version or fresh install:**

**List of activated apps:**

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - bookmarks: 10.4.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.8
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.1
  - files_automatedtagging: 1.11.0
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.1.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - forms: 2.4.0
  - groupfolders: 9.0.4
  - guests: 2.1.0
  - impersonate: 1.8.0
  - integration_discourse: 1.0.0
  - integration_whiteboard: 0.0.14
  - integration_zammad: 1.0.1
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notes: 4.3.1
  - notifications: 2.9.0
  - notify_push: 0.4.0
  - oauth2: 1.9.0
  - onlyoffice: 7.3.2
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 3.6.1
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.13.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.3.6
  - support: 1.4.0
  - survey_client: 1.9.0
  - suspicious_login: 4.1.0
  - systemtags: 1.11.0
  - tasks: 0.14.4
  - text: 3.2.1
  - theming: 1.12.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_nextcloud_notification: 3.3.1
  - twofactor_totp: 6.3.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.2
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - welcome: 1.0.0
  - workflowengine: 2.3.1
Disabled:
  - encryption
  - federation: 1.3.0
  - files_external
  - firstrunwizard: 2.2.1
  - globalsiteselector
  - nextcloud_announcements: 1.7.0
  - sendent: 1.2.12
```

#### Client configuration
**Browser:**
Firefox
**Operating system:**
Win 10

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/twofactor_totp/issues/1006 and apparently fixed in the meantime.

Beware you are running a version of Nextcloud that has reached end of life: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by hartsberger** [comment]
Sorry, I did not find that issue bevor opening my own. 

Thanks for the hint, I know that I am a bit in delay 😬
