### ISSUE TITLE
WebDavCal will not sync with TOTP activated

### ISSUE THREAD

**Issue by kevdogg** [nextcloud/twofactor_totp#124]
Hi 
Running NextCloud 11.0.1 with TOTP plugin in 0.5.0.  I can confirm accessing the WebDav Calendars worked prior to activating TOTP, and if I deactivate plugin, sync will again work.

With TOTP activated -- I tried using both the app-specific passwords and backup passwords -- both which dont seem to work.  I've looked in the logs of nextcould and I don't see anything generating an errror. Clients for WebDAV are both iOS and MacOSX.

**Comment by ChristophWurst** [comment]
Hi,

it's expected that your login password is not accepted if your account is two-factor protected. However, app-specific passwords *should*d work. Did you use the very same username that you've used when you logged into your Nextcloud to generate the code?

Some info about your setup would also be quite helpful, e.g. the apps you're using and steps to reproduce the problem. Thanks

**Comment by simuuh** [comment]
@ChristophWurst This works for me.
