### ISSUE TITLE
Passwordless authentication should not require TOTP token

### ISSUE THREAD

**Issue by raQai** [nextcloud/twofactor_totp#1246]
Setting up Passwordless Authentication and 2FA using the TOTP app leads to 3FA since the TOTP token is required even if using a hardware device token to log in. This essentially is 3FA which undoubtedly is more secure but kind of annoying. It would be better to avoid TOTP when Passwordless Authentication is used but keep it when logging in using a password (e.g. as a backup 2FA). Might even be considerable to make this optional using a check box.

### Steps to reproduce
1. Setup "Passwordless Authentication" using a FIDO2 key
2. Log out
3. Go to login page
4. "Log in with a device"
5. Touch token

### Expected behaviour
Using the correct FIDO2 key should directly log in the user.

### Actual behaviour
Using the correct FIDO2 key leads to the TOTP page.

### Server configuration (hosted by Hetzner)

**Version:** 24.0.1
**List of activated apps:** Probably irrelevant to this issue

#### Client configuration

**Browser:** Firefox (any version) and Chromium (any version)
**Operating system:** Fedora 36

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/21215
