### ISSUE TITLE
Enabling 2FA breaks Calendar on IOS

### ISSUE THREAD

**Issue by aredey** [nextcloud/twofactor_totp#1249]
I have enabled 2FA on my Nextcloud using this app. It stopped my iphone/ios calendar communicating with the my nextcloud instance through CalDAV, the phone pops up a "Password Incorrect" error, presumably it wants to use the authenticator generated number but the phone calendar app has no way to handle this I found. Is this a known issue? Or is there a work around described anywhere?

**Comment by pim-wtf** [comment]
To use CalDAV with 2FA enabled, you need to create an **app password**. Go to Settings > Personal > Security and scroll all the way down. There you'll see a button "Create new app password". Click it and it will create a unique username/password combination that can be used for authenticating CalDAV on the iOS Calendar app.

**Comment by aredey** [comment]
Brilliant, many thanks - i couldn't find this item buried under all my existing sessions!
