### ISSUE TITLE
App Certificate is not valid on ownCloud 9.1.3-1.1 vmware

### ISSUE THREAD

**Issue by akeilox** [nextcloud/twofactor_totp#125]
I have just started using owncloud from a vmware official image, 9.1.3 version,

Under Apps, enabled experimental and tried adding twofactor_totp but its giving the following error:

How should I go about fixing the App Certificate is not valid error? 
Would greatly appreciate if someone can shed some light on this:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- twofactor_totp
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- App Certificate is not valid.

Raw output
==========
Array
(
    [twofactor_totp] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => App Certificate is not valid.
                )

        )

)

**Comment by ChristophWurst** [comment]
> How should I go about fixing the App Certificate is not valid error?
> Would greatly appreciate if someone can shed some light on this:

One solution is to use Nextcloud. This app does not support ownCloud, hence I won't fix that certificate problem.

**Comment by DeepDiver1975** [comment]
@akeilox there is an owncloud compatible version now in the appstore: https://apps.owncloud.com/content/show.php/TOTP+TwoFactor+%28Google+Authenticator%29?content=174726
