### ISSUE TITLE
NC 25 2fa icon missing under mobile web at logon

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/twofactor_totp#1260]
### Steps to reproduce
1.Sign into nextcloud via mobile web
2.enter username & password 
3.get 2fa screen 

![Screenshot_20220902-154308_Chrome.jpg](https://user-images.githubusercontent.com/59488153/188233485-e208673d-6a49-485c-bddf-4a9b922cc9e7.jpg)

**Comment by PocketFR** [comment]
The SVG icon is white, as is the background.
You can change the color of the icon or add
```
.two-factor-icon {
background-color: var(--color-primary);
border-radius: 10%;
}
```
in the style.css file of the app
