### ISSUE TITLE
"Two Factor TOTP Provider" can't be activate after upgrade to 11.0.1 on nextcloud box.

### ISSUE THREAD

**Issue by jlicher** [nextcloud/twofactor_totp#127]
After the automatic update to 11.0.1 of the nextcloud box, "Two Factor TOTP Provider" was deactivated and can't be activated. The errormessage was `"Two Factor TOTP Provider" cannot be installed because the following dependencies are not fulfilled: PHP with a version lower than 7.0 is required.`. There was no possibility or message to update the app. The only solution was to uninstall the app and install it again. Is there a problem wit updates at the moment?

**Comment by ChristophWurst** [comment]
Hi,

when did you perform the update? I just released a new version of this app today, before there was no php7.1 compatible release available unfortunately.

**Comment by mikejkeen** [comment]
I had the same problem using the nextcloud snap. I upgraded to 11.0.1snap1 a few days ago in which [php was upgraded to 7.1.1](https://github.com/nextcloud/nextcloud-snap/releases/tag/11.0.1snap1) It appears that is what caused the problem. It seems you've updated and the nextcloud-snap project just released an update to [downgrade to 7.0.15](https://github.com/nextcloud/nextcloud-snap/releases/tag/11.0.1snap2), so the problem should clear up either way on those fronts.

**Comment by jlicher** [comment]
I performed the update last weekend. I dont know, how often the checks for app updates are peformed, but even yesterday evening i got no informations about an update.

**Comment by ChristophWurst** [comment]
Any update? Does it work with the most recent release v1.1?

**Comment by weitlaner** [comment]
I have the same problem with a self-hosted NC installation running on php7. NC Version 11.0.1, TOTP 1.1.0. (see screenshots).

![bildschirmfoto 2017-02-18 um 16 32 25](https://cloud.githubusercontent.com/assets/3775413/23094398/8495d5b6-f5f8-11e6-9b8d-31f3cbbefe6c.png)
![bildschirmfoto 2017-02-18 um 16 31 28](https://cloud.githubusercontent.com/assets/3775413/23094397/8495ad02-f5f8-11e6-96df-968d9209120d.png)

**Comment by ChristophWurst** [comment]
No response from the OP -> closing

@weitlaner your issue is unrelated and shouldn't have happened with the recommended installation process. However, thanks for sharing your fix 😉
