### ISSUE TITLE
Difficult displaying in Google Authenticator

### ISSUE THREAD

**Issue by ktbgh** [nextcloud/twofactor_totp#1271]
Hi,

I have some NC environments. When I activate TOTP (Version 6.4.0) with Google Authenticator, I see with new installed NC24 Environments in GA Entries like this:

Nextcloud (username1@domain1)
Nextcloud (username2@domain1)
Nextcloud (username1@domain2)
Nextcloud (username2@domain2)
Nextcloud (username1@domain3)
Nextcloud (username2@domain3)

In past with NC 23 (and TOTP Version 6.2.0) I see in GA

domain1 (username1@domain1)
domain1 (username2@domain1)
domain2 (username1@domain2)
domain2 (username2@domain2)
domain3 (username1@domain3)
domain3 (username2@domain3)

This means in NC23 GA usage I had a very better 1st view when GA using on mobile phone.
Now with NC24 I only see "Nextcloud (username1@do" and must always draw the screen, when I want to see the full line.
It is not possible, changing in GA the name. 

Q: Is it possible set the "GA-Name" when creating TOTP Code? Or set it system wide?

Thanks for your support
Regards
Karl

**Comment by st3iny** [comment]
Yes, the name is taken from the theming config. It is set to the configured name of your instance and will default to "Nextcloud".

You can customize the name either by running `occ theming:config name mycloud` or in the settings at `Admin Settings -> Theming -> Name (input field)`.
