### ISSUE TITLE
NC 25 Theme issue first time setup

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/twofactor_totp#1280]
### Steps to reproduce
1.Creat new user
2.have user login
3.
![image](https://user-images.githubusercontent.com/59488153/194640293-3ed66689-723f-4db0-bcbe-d7610f7a8d8d.png)

**Comment by andyxheli** [comment]
Changed width: 300px and seemed to have fixed this. Can someone please let me what file i need to change so i can create a PR
![image](https://user-images.githubusercontent.com/59488153/194643593-19d7d4db-7ef8-4baf-b191-34cb7b3835e6.png)

**Comment by andyxheli** [comment]
Or should you prefer this ?

display: inline-flex;
width: 300px !important;

![image](https://user-images.githubusercontent.com/59488153/194644391-42b870d6-2231-4130-ac61-ac680b60b369.png)
