### ISSUE TITLE
Changelog in /settings/apps sidebar info, CHANGELOG.md, Releases

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_totp#1284]
Today, 6.4.1 was released. CHANGELOG.md is not up-to-date (says 6.4.0 RC1, 4 months ago). As admin, I look in the /settings/apps sidebar. Apps show the latest changes there if provided in appinfo/info.xml and the App store meta data. twofactor_totp should do that, too. And make sure CHANGELOG.md is up-to-date prior to building a release.

Personally, I also find it irritating that releases are not available in GitHub for download. But that might be my own misunterstanding/misinterpretation. Is it OK to only upload to the app store? What is the intented way?

**Comment by ChristophWurst** [comment]
The release is on github: https://github.com/nextcloud-releases/twofactor_totp/releases/tag/v6.4.1

You are right, I forgot to update the changelog. The only change in .1 is https://github.com/nextcloud/twofactor_totp/pull/1281. If there is a .2 I will add the changelog there.

> Is it OK to only upload to the app store? What is the intented way?

The app store doesn't host the package so you always need to upload it somewhere.

**Comment by nursoda** [comment]
What about the sidebar?! (I just added screenshots to my initial message.)

**Comment by ChristophWurst** [comment]
I don't know the logic behind the sidebar contents.
