### ISSUE TITLE
Icon for TOTP provider app

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/twofactor_totp#129]
Sadly I have no real idea what an icon could look like, but maybe @eppfel or @skjnldsv  or any other in @nextcloud/designers has an idea.

Then we could also use this in the personal settings (see nextcloud/server#3151) as sidebar icon.

cc @ChristophWurst

**Comment by ChristophWurst** [comment]
Yup I remember @jancborchardt and I talked about that at the Winzerhof hacking when I made the u2f logo. I think a phone icon could fit this app.

**Comment by skjnldsv** [comment]
With a key inside?

**Comment by stefan-niedermann** [comment]
Or maybe with a key next to it? This is how the new Nextcloud Phone Sync logo could look like: https://github.com/nerzhul/ownCloud-SMS-App/pull/118#issuecomment-267283056

**Comment by eppfel** [comment]
> Or maybe with a key next to it? This is how the new Nextcloud Phone Sync logo could look like: 

I think adding it beside, adds too much details compared to the other icons.
<img width="86" alt="bildschirmfoto 2017-01-25 um 11 25 20" src="https://cloud.githubusercontent.com/assets/1899308/22286968/530e9aa6-e2f1-11e6-9615-0e256f426d38.png">

**Comment by Bugsbane** [comment]
What about a small keyring with 2 keys on it? Heh, looks like someone else had the same idea (although I'd make the ring a bit smaller to give the keys more emphasis):
![2 Factor](https://cloud.githubusercontent.com/assets/401733/22362818/99b742d0-e433-11e6-9e96-bf28807904f3.png)
from:
https://thenounproject.com/search/?q=two+factor&i=467407
