### ISSUE TITLE
Don‘t ask for TOTP when logging in using WebAuthn

### ISSUE THREAD

**Issue by tkriener** [nextcloud/twofactor_totp#1318]
### Feature Request

If I login using WebAuthn I still have to provide a TOTP.
It would be good, if the TOTP could be overleapt if WebAuthn is used for authentication, just like with device passwords.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/21215. Unless we enforce a PIN for WebAuthn your login will *not* be 2FA'd.
