### ISSUE TITLE
2FA on Mobile App

### ISSUE THREAD

**Issue by dave510** [nextcloud/twofactor_totp#132]
When I enabled 2FA I was no longer able to sign in to Nextcloud's mobile app. I got a 401 error. Is this an issue with the app or is there additional configuration for using it with the app?

Thanks!

**Comment by ChristophWurst** [comment]
Hi,

create app passwords as documented in https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices (you'll find that in your personal settings) 😉
