### ISSUE TITLE
Token unsafe in FreeOTP

### ISSUE THREAD

**Issue by mvvvmd** [nextcloud/twofactor_totp#1324]
### Steps to reproduce
1. Enable 2fa
2. Scan the QR code using FreeOTP on Android

### Expected behaviour

The account should be added without error
 
### Actual behaviour
Tell us what happens instead

Get the warning "Token is unsafe!"

The token should apparently have at least have at least 128bit and not trigger the error then.

https://github.com/freeotp/freeotp-android/issues/287
https://www.ietf.org/rfc/rfc4226.txt

**Comment by ranvis** [comment]
@nickvergessen
Thank you for the update.
Actually, it is in base 32; 5-bit per char.
I think 160 / 5 = 32 bytes should be enough.

**Comment by nickvergessen** [comment]
Thanks!
