### ISSUE TITLE
TOTP does not work with Windows phones request alternative

### ISSUE THREAD

**Issue by chogumchonsa** [nextcloud/twofactor_totp#133]
Good day, 

I have a client trying to use a Windows phone to access our website which is configured with TOTP. Would anyone have any alternative methods for my client to use for his mobile device. Thank you in advanced. 

~j

**Comment by ChristophWurst** [comment]
Hey,

create an app password in your personal settings and use it to configure your client ;-)

**Comment by chogumchonsa** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Would love to tell my client that however he is very insistent  on using his windows phone. Thank you 


Sent from Yahoo Mail for iPhone


On Saturday, January 28, 2017, 03:27, Christoph Wurst <notifications@github.com> wrote:


Hey,

create an app password in your personal settings and use it to configure your client ;-)

**Comment by ChristophWurst** [comment]
what?

**Comment by chogumchonsa** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } I asked him to use the desktop app. He said he wanted to use totp but only has a windows phone. 


Sent from Yahoo Mail for iPhone


On Monday, January 30, 2017, 11:55, Christoph Wurst <notifications@github.com> wrote:


what?

**Comment by ChristophWurst** [comment]
Hello,

I did not mean that you have to use the desktop app. You can of course use any other compatible app, but you'll have to generate an app password if the Nextcloud account is two-factor protected as we don't allow password logins then. See https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices for more information 😉

**Comment by chogumchonsa** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thank you Mr. Wurst. 


Sent from Yahoo Mail for iPhone


On Monday, January 30, 2017, 15:57, Christoph Wurst <notifications@github.com> wrote:


Hello,

I did not mean that you have to use the desktop app. You can of course use any other compatible app, but you'll have to generate an app password if the Nextcloud account is two-factor protected as we don't allow password logins then. See https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices for more information 😉

**Comment by ChristophWurst** [comment]
(I assume you didn't see that in your mail client, but your response looks a bit weird here on GitHub. I did not see your reply at first)

**Comment by chogumchonsa** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Thank you for responding. I have them using a desktop client to achieve totp. 


Sent from Yahoo Mail for iPhone


On Monday, January 30, 2017, 15:58, Christoph Wurst <notifications@github.com> wrote:


(I assume you didn't see that in your mail client, but your response looks a bit weird here on GitHub. I did not see your reply at first)

**Comment by ChristophWurst** [comment]
See my message above. The desktop client does not solve the problem. You simply cannot use the login password for *any* client if TOTP is enabled. Use an app-specific password instead.
