### ISSUE TITLE
2FA breaks NextCloud client

### ISSUE THREAD

**Issue by copenhaus** [nextcloud/twofactor_totp#134]
just want to point out that enabling 2FA breaks the NextCloud client in Windows and Anroid.

I am sure this will need the coordination with Client team to sort this out.

**Comment by ChristophWurst** [comment]
It doesn't. I assume you've used your login passwort to configure the client, which we diallow as soon as 2FA is enabled for your account. Generate and use an app password instead. You can generate one in your personal settings.

**Comment by copenhaus** [comment]
I found the "App passwords"!!

TOP NOTCH!

**Comment by fundy77** [comment]
HI, although creating an app-password enables android client to login, no download of any files is possible with an app-specific password.

**Comment by ChristophWurst** [comment]
Hey @fundy77,

could you please file a new ticket and provide more information about your specific setup? You can use https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md as a guide :-)
