### ISSUE TITLE
Please bump to NC 26

### ISSUE THREAD

**Issue by MarkWieczorek** [nextcloud/twofactor_totp#1341]
Nextcloud 26 was released, but there is not yet a compatible version of this app.

**Comment by lugau45** [comment]
Please update for php 8.2, with php 8.1 it works under nc26

**Comment by ChristophWurst** [comment]
This app is *shipped*. It should come with the installation/upgrade of Nextcloud 26.

**Comment by zingmars** [comment]
@ChristophWurst So what's the update procedure for those who are running Nextcloud from git then? This is the only app that I've seen that doesn't update properly with that set-up.

**Comment by ChristophWurst** [comment]
The same as any other shipped apps. I can't give more support for this. Use https://help.nextcloud.com/c/support/7.
