### ISSUE TITLE
how do you sign into pasword only applications using totp?

### ISSUE THREAD

**Issue by lachlan-00** [nextcloud/twofactor_totp#136]
I would like to enable totp but when i do i'm only able to sign into the web application.

How can you sign into online accounts in gnome or set up dav/cal connections when everything except the nextcloud front page uses user and pass?

**Comment by ChristophWurst** [comment]
Hey @lachlan-00,

you'll have to generate app passwords in your personal settings, see https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices 😉
