### ISSUE TITLE
Save devices

### ISSUE THREAD

**Issue by tomaaa** [nextcloud/twofactor_totp#138]
Hi,
It would be nice to register the device so after registered, it will not prompt for the two factor because it it registered.

It's bad to type it every time .

**Comment by ChristophWurst** [comment]
Hey,

we have a ticket for this feature request somewhere, but I'm unable to find it at the moment. Basically this would require a change in the server component, not this app.

**Comment by MariusBluem** [comment]
https://github.com/nextcloud/server/issues/2906

**Comment by ChristophWurst** [comment]
Thanks @MariusBluem :)
