### ISSUE TITLE
Use authentication keys as 2nd factor

### ISSUE THREAD

**Issue by Altair31** [nextcloud/twofactor_totp#1381]
### Feature Request

Today, we can register in Nextcloud authentication keys like Yubikey to replace password authentication.
As a user I would prefer use it as 2nd factor instead of OTP.

#### Summary
Today, we can authenticate with 2FA using the following factors:
- Password + OTP
- Key + OTP

My feature request:
- Password + Key

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/twofactor_webauthn
