### ISSUE TITLE
Calendar / external

### ISSUE THREAD

**Issue by criwe** [nextcloud/twofactor_totp#140]
Hi!
The app works like charm. 

But when using the calender app and embed it in an external client (i.e. thunderbird) syncing isnt possible anymore. After deactivating the 2fa-app, syncing works fine again.

On the one hand, thats logic - to sync a calendar passwort/username is needed, therefore the the second factor too -, on the other hand, theres no option - afaik - to use the 2fa-app and externel embeded calenders?

Any ideas/opinions?
Best
Chris

**Comment by ChristophWurst** [comment]
Hey Chris,

see [the user manual](https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices) on how to connect devices. Basically, you'll have to use an app-password instead of your login password.

**Comment by criwe** [comment]
Hi Christoph,
thx a lot! Works fine :-)
Best
Chris
