### ISSUE TITLE
Android app login broken

### ISSUE THREAD

**Issue by Pablohn26** [nextcloud/twofactor_totp#143]
I have been testing and It seems this plugin break the login with Android Nextcloud app.

When twofactor_totp is disable there is no problem with the login but once I enable it the login drops an error of "login incorrect".

To reproduce it, just enable this plugin and then try to login using Android app.

Versions: 
Nextcloud 11
Android 6
Nextcloud Android app: 1.4.1
FreeOTP 1.5

**Comment by MariusBluem** [comment]
See #136 😜
