### ISSUE TITLE
TOTP not working 

### ISSUE THREAD

**Issue by fletcherfletch** [nextcloud/twofactor_totp#1444]
### Steps to reproduce
1. Fix the totp
2.
3.

### Expected behaviour
the otp should be accepted and should be logged in 

### Actual behaviour
When I tried to login my nextcloud account which is hosted in my internal server , the totp otp put gives an error for which I can’t login into my nextcloud , it’s happening to every user , I have forced disabled two factor . But I want it to work

### Server configuration

**Operating system**:
Ubuntu 
**Web server:**

**Database:**

**PHP version:**

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by ChristophWurst** [comment]
> ### Steps to reproduce
> 
>     1. Fix the totp
> 
> 
> ### Expected behaviour
> 
> the otp should be accepted and should be logged in

Closing as there is no clear description of what is wrong.
