### ISSUE TITLE
Translate your app

### ISSUE THREAD

**Issue by ckykenken** [nextcloud/twofactor_totp#145]
How can I translate the app? I searched in Transifex and I can't find your app.

**Comment by MariusBluem** [comment]
We use Transifex for this app too: https://www.transifex.com/nextcloud/nextcloud/twofactor_totp/
Would be awesome if you help us translating - reviewing - and making Nextcloud TOTP better translated 💪

**Comment by ckykenken** [comment]
Done!

**Comment by ChristophWurst** [comment]
Cool, @ckykenken, thank you very much :-)
