### ISSUE TITLE
Problem with CalDAV auth

### ISSUE THREAD

**Issue by paltish-com** [nextcloud/twofactor_totp#1457]
### Steps to reproduce
1. Connect iOS or MacOS to Calendar or task app
2. After activation this app

### Expected behaviour
System can't understading 2FA in this auth protocol

### Actual behaviour
Tell us what happens instead

### Server configuration

Not depend

#### Client configuration
CalDAV
iOS or MacOS

**Comment by ChristophWurst** [comment]
Use app passwords

**Comment by paltish-com** [comment]
Hello, @ChristophWurst . I'm sure you haven't tried what I'm writing to you about. because I enter the password, and in general I have experience in troubleshooting. It's a pity that you closed the problem without understanding it. If you disable 2FA, the problem goes away.
I hope this will be fixed someday, have a nice day.

**Comment by ChristophWurst** [comment]
If your login password can be used to access CalDAV data, what is the point of two-factor authentication?

What you describe as bug is a security feature. 

See https://docs.nextcloud.com/server/latest/user_manual/en/user_2fa.html#using-client-applications-with-two-factor-authentication.

**Comment by paltish-com** [comment]
When you turn on application TOTP in profile-->security section, you are lost CalDAV connection. You have two ways to change the situation:

1. Turn off TOTP plugin
2. Create new app password in Devices & sessions section on security page. (It's not obvious)

But thanks for the answer. Have a good day.

**Comment by Sofahamster** [comment]
It's an old issue but: This still doesn't work properly. I do use app passwords, have done so since the beginning. But the moment I enable TOTP, Thunderbird fails to sync the calendars. If I disable TOTP for my account, syncing works again. I created a fresh app password after enabling TOTP and tried to use that in Thunderbird, but that fails, too. Thunderbird will initially connect and show the available calendars for subscription, but will then fail to actually access them.

**Comment by StefanPp** [comment]
Same issue. I can confirm this behaviour.
NC Hub 8, TB 128.
Interesting: I also use the Addon "CardBook" on TB to synchornise Contacts, works pretty well.
In password-storage I can see the generated and stored app-passwords correctly.

Maybe a problem with TB Calendar-Addon?

**Comment by jclsn** [comment]
Same issue here. Why is this closed?

**Comment by ChristophWurst** [comment]
Because the issue is resolved. You have to use app passwords in combination with 2FA. Changing passwords in TB doesn't always have immediate effects. When switching from login password to an app password restart TB. If that doesn't help restart your computer. Then it will work.

**Comment by jclsn** [comment]
Right, that works. Should probably be mentioned in the Security page where you configure TOTP that you have to use App passwords then!

**Comment by jclsn** [comment]
It is mentioned actually, but not explained well enough. I think something like

Note: If you are using CalDAV or CardDAV with you login password currently, this won't work anymore. For use with 2FA, app passwords are required!

would be better

**Comment by Sofahamster** [comment]
As I had written in my comment above, I did use app passwords. I did use app passwords even before I activated 2FA. It did not work in Thunderbird with 2FA enabled. I don't know why and I no longer care, because I disabled 2FA, so that I can use the calendar.

**Comment by ChristophWurst** [comment]
Thank you for your feedback!
