### ISSUE TITLE
unable to login after upgrade to 11.0.2 when using 2FA

### ISSUE THREAD

**Issue by laurensqq** [nextcloud/twofactor_totp#147]
I have been using 2FA for a bit now and noticed i was unable to login to my account after upgrading to 11.0.2

i am using LDAP user, also tested with local NC user but keeps saying that the code is incorrect.
tested on our test VM and on a clean backup from nexcloud 10 i updated to 11.0.2

**Comment by ChristophWurst** [comment]
Could be related to https://github.com/nextcloud/twofactor_totp/issues/123, were I still could not figure out what's going on.

Did you check whether the clocks on your server and smartphone are in sync? Time drifts problems too.

**Comment by laurensqq** [comment]
seems like it was caused by a combination of the 2.
logged in using backup code and disabled it and reenabled it.
also updated the time, was a bit off.

**Comment by ChristophWurst** [comment]
Could you, by any chance, try to reproduce the bug again and try the two solutions separately to isolate the bug? That would be awesome :-)

**Comment by laurensqq** [comment]
took a backup before testing so should be able to reproduce by reverting to backup.

**Comment by laurensqq** [comment]
Seems that time drift was the issue, since i could log in fine after correcting that first

**Comment by ChristophWurst** [comment]
Great, I was hoping it just being a time drift 😀 Thanks a lot!
