### ISSUE TITLE
TOPT just dont take my pass from app

### ISSUE THREAD

**Issue by techgeeksvk** [nextcloud/twofactor_totp#1497]
Steps to reproduce:
1.Standart login
2.Add 6 pin pass
3.Something went wrong 

I got NEXTCLOUD on unraid server with linuxserver.io. App that is installed is version 10.0.0. beta.2. Don´t know what i should do. Never happend something like this. Nextcloud is uptated to latest version of linuxserver.io docker. Thanks for help guys.

**Comment by ChristophWurst** [comment]
Please use https://help.nextcloud.com/c/support/7 for community support.

Make sure the clock on your server and your phone are in sync.
