### ISSUE TITLE
documentation needed: how to 

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_totp#151]
Lukas [wrote](https://statuscode.ch/2017/03/why-is-it-important-to-run-nextcloud-to-keep-your-data-safe): "When two-factor authentication is enabled, external applications that have access to Nextcloud, like a Calendar app on your phone, for example, can be denied access to the file system in Nextcloud 11; we recommend you to enable that."

I tried fo find out how to do that but did not find ANY documentation on that. Neither in the user manual "How to use 2FA" nor in Admin manual, "Hardening" section, nor in my Nextcloud (checked "Administration" and "User Profile"). Please document and post the link here.

Apart from that, once a user has the NC app on his phone (not using a separate, stripped-down user account), this security enhancement is questionable, right?

**Comment by ChristophWurst** [comment]
I think he's talking about app passwords and the ability to restrict access to the file system. App passwords are documented in https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices

Generally, this is totally independent from the totp app, so it would be great if we could move this discussion to the forum, help.nextcloud.com. Thanks.

cc @icewind1991 @LukasReschke

**Comment by nursoda** [comment]
I found it:

![grafik](https://cloud.githubusercontent.com/assets/8425483/23665370/8a11e36e-0358-11e7-9ba8-6071a93a5e04.png)

**Comment by ChristophWurst** [comment]
No worries. If you'd like to help us improve the documentation of app-passwords, you can find the documentation [here](https://github.com/nextcloud/documentation/blob/master/user_manual/session_management.rst) – pull requests are very welcome 😉
