### ISSUE TITLE
RFE: "Remember this browser" (set cookie)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_totp#152]
Major sites allow users to not having to enter their credentials EVERY time but only if
- they use it the first time in a browser session (non-persistent)
- they did not successfully log in within e.g. 30 days on this browser (persistent, valid-until set) or if
- they never used this browser before (or cookies were cleared) (permanent, like fb).

This would enhance user experience for security aware users (using TOTP to prevent anyone bruteforcing their password from anywhere in the world) quite a lot, because one doesn't need to set a "remember my complete logon" cookie but may choose to skip one step on trusted systems.

**Comment by rigrig** [comment]
This makes sense, but is something that applies to all 2FA methods, not just TOTP.
That means it would have to be implemented in the core server, instead of this app.
An issue for this already exists in the server repo: https://github.com/nextcloud/server/issues/2906

**Comment by ChristophWurst** [comment]
Agreed, let's continue there :)
