### ISSUE TITLE
RFE: reverse-sort App-PINs or add a heading while showing new entry

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_totp#153]
This is what it looks like if one already has one App-PIN and adds another:

![grafik](https://cloud.githubusercontent.com/assets/8425483/23666337/051ead4c-035b-11e7-8bed-df7f94071105.png)

This is irritating since it looks like this PIN would belong to "Nextcloud-App" due to proximity. In fact, it's the "test" PIN. Easiest would be to reverse sorting. Another option was to add some delimiter and a heading that clearly states the whole new entry, including the name it was given.

**Comment by ChristophWurst** [comment]
Please open this feature request at https://github.com/nextcloud/server/issues/new, this is the issue tracker of the *totp 2fa provider*.
