### ISSUE TITLE
When enable 2FA, QR code not showing up.

### ISSUE THREAD

**Issue by tjberte** [nextcloud/twofactor_totp#155]
Screenshot.  Am I missing something?

![image](https://cloud.githubusercontent.com/assets/4635314/23832359/3766e348-0700-11e7-81eb-4d0262fa870d.png)

**Comment by ChristophWurst** [comment]
Hey,

could you please tell me more about your setup? How did you install the app? Via the app store?

**Comment by ChristophWurst** [comment]
Wild guess: did you install the app by copying the code from github into the `apps` directoy?

**Comment by tjberte** [comment]
Yes, I actually did because AWS was acting up.  That worked!  I deleted the folder and re-installed via app menu.  Good to go.
