### ISSUE TITLE
2FA QR not going to Google Authentictor

### ISSUE THREAD

**Issue by jet438** [nextcloud/twofactor_totp#1561]
Please ask your question(s) at https://help.nextcloud.com/c/apps/twofactor-totp.

**Comment by jet438** [comment]
Sorry about that. The issue opened without it letting me to post the message.
The issue I'm having is that the QR code isn't triggering an add for authenticator. Instead it's sending me to Google play

**Comment by ChristophWurst** [comment]
Please ask your question at https://help.nextcloud.com/c/support/7
