### ISSUE TITLE
I cannot see Two-Factor TOTP in my available apps

### ISSUE THREAD

**Issue by martynbiz** [nextcloud/twofactor_totp#1579]
Hi,

I'm running Nextcloud Hub 8 (29.0.3) as a Docker instance on my own server.

I can see lots of Two-Factor apps under the Security tab, but I can't see Two-Factor TOTP listed. Is there any reason why this might be? Is the server environment perhaps not setup correctly to support this app thus it won't show? 

Thanks
Martyn

**Comment by ikkemaniac** [comment]
@martynbiz it's not listed in the securities category for some reason. you can find it in the featured category of use the search on the top of the page to find it.

**Comment by Justinzobel** [comment]
How do we help get this tested on newer versions so it shows up nicely on https://apps.nextcloud.com/apps/twofactor_totp?
