### ISSUE TITLE
Add possibility to add multiple TOTP devices

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/twofactor_totp#158]
Something like https://github.com/nextcloud/twofactor_u2f/pull/40 just for TOTP 😜 

What do you think? @ChristophWurst

**Comment by ChristophWurst** [comment]
Already supported, just scan the QR code with all your apps/devices, just like on GitHub. Ref https://help.github.com/articles/configuring-two-factor-authentication-via-a-totp-mobile-app/

**Comment by MariusBluem** [comment]
Well ... yes :D But this does not give you the option to revoke a single device if lost... and the QR code does only appear once, and it would require you to save the QR code - or to reconfigure every device if you want to add one 😅

**Comment by ChristophWurst** [comment]
Sure, but it's not possible security-wise. We'd have to check x OTP secrets on login, because we don't know which of your x devices is used. This trial and error method would break the necessary effort to guess the TOTP key by x. I doubt this is what we want :-)

cc @LukasReschke because I'm not 100% sure if the above is true, it's just my assumption of how this would work.

**Comment by MariusBluem** [comment]
sounds logical. And an option to show the QR-code again? 😁

**Comment by ChristophWurst** [comment]
Dunno if that's a good idea …

**Comment by astriffe** [comment]
... sorry for hijacking, but: What can I do if I got a new phone in order to register it? There's no QR code displayed and I'd really like not to loose all app-passwords. Can I transfer the TOTP information from my old phone to the new one?

**Comment by MariusBluem** [comment]
Depends on whether your TOTP client supports that natively. You may also want to save your QR-code (or the text-based code) before the codes are hidden - then you could register every device you want - everytime 💪 @astriffe

**Comment by astriffe** [comment]
Thanks a lot for your swift response @MariusBluem. To save the QR code when scanning would probably deserve a prominent place in the docs ;) I'm using https://github.com/0xbb/otp-authenticator as a second factor. Do you know whether the code is stored in clear text on my server? Or is there no way around re-initializing everything? Cheers

**Comment by Gijom** [comment]
Just my two cents: saving the QR code somewhere unsafe is not secured: enybody who has access to it would be able to enter the 2nd auth code (but still need your password before that).
You would need to save the QR code in a safe place.

I recommend pass and pass-otp for that. Pass-otp can regenerate the QR code from the URI if needed. To get the URI from the QR code you can use zbar.

**Comment by emilioalaca** [comment]
I use 2FA for other institutions and they naturally allow multiple devices. This thread makes me think that they are not really secure. As a method, I usually doubt what I think, but in this case I am having great difficulty believing myself ;-). Help?

**Comment by davidbonnet** [comment]
Note that [AWS](http://aws.amazon.com) also allows for multiple devices to be registered.

**Comment by Clemens85** [comment]
Why is this issue closed? It is still not possible to add multilple authenticator apps (which is really useful if you have e.g. a second mobile phone).
You made MFA mandatory, then make it also more usable...

**Comment by pkgadd** [comment]
With the push to force 2FA on all users, there really needs to be support for multiple (independent) TOTP devices. Right now I have to rely on a single smartphone as TOTP authenticator (and the recovery codes), which does not -at all- provide peace of mind.

passkeys/ security keys are a nice concept, and I'd actually like to add them - but again, I'd need at least two or three to feel comfortable about passkey-device failure, and that gets expensive really fast, so no.

SMS/ text message: no, I'm not handing out my cell phone number to anyone but first degree family members. Not going to happen, I'd rather close my account.

github mobile app: nope, not adding $x special apps, one for each service I'm subscribed to
