### ISSUE TITLE
Bad url to get javascript

### ISSUE THREAD

**Issue by crequill** [nextcloud/twofactor_totp#162]
Hi
On an installation of TOTP 1.1.0 on nextcloud 11.0.2 on Archlinux, personal page search to get some javascript url but this fail:
GET /cloud/wapps/twofactor_totp/js/settingsview.js
On my server, TOTP is installed in /cloud/apps2/twofactor_totp. So the url failed.
To run it, I create a soft link between /cloud/apps2 and /cloud/wapps.
But this is not a good solution. Can you get the right path, please ?

**Comment by ChristophWurst** [comment]
Hi,

this is strange. I'm including the js file like any other, with the standard helper functions: https://github.com/nextcloud/twofactor_totp/blob/7291a35b36986bdc6adea8935aa0156fc98e257f/templates/personal.php#L3.

Does it only fail to include this one file or also others like the `settings.js` file?

Do you experience problems with other apps too?

**Comment by crequill** [comment]
Yes it is for settingsview.js and settings.js. I have these two errors.
No problem with the others applications already installed with nextcloud.

**Comment by crequill** [comment]
For information, apps2 is a [custom app directory](https://docs.nextcloud.com/server/11/admin_manual/installation/apps_management_installation.html#using-custom-app-directories) The others apps are installed by default and are in apps directory. Totp is the only application I added and running in apps2.

**Comment by ChristophWurst** [comment]
Thanks for the feedback. Could you please the relevant config here, e.g. by using `php occ config:list system` and `php occ config:list twofactor_totp`.

**Comment by crequill** [comment]
OK sorry I don’t remember the url I put for apps2:
`"apps_paths": [
            {
                "path": "\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/webapps\/nextcloud\/apps2",
                "url": "\/wapps",
                "writable": true
            }
        ],`
It's not a bug for otp: it’s a bug in my config.

**Comment by ChristophWurst** [comment]
Great to hear you could solve the problem! 😄
