### ISSUE TITLE
unable to login after 2FA app disabled

### ISSUE THREAD

**Issue by molnarti** [nextcloud/twofactor_totp#167]
The Nextcloud updater disabled the 2FA app on my server. As a result I am unable to login into nextcloud, as my password is rejected, and I also cannot re-enable the app, as it requires authentication too. I tried using the backup codes for authentication, but to no avail. Any suggestion?

**Comment by ChristophWurst** [comment]
> Any suggestion?

Yes, please provide more details about your setup. Which version before/after the upgrade, which app version, error log, environment (hosted, own server) and so on.

Generally, if the app gets disabled you should be able to log in with your password. I don't see a reason why that wouldn't be allowed anymore – did you forget your password?

On a side note, the app won't get disabled during an upgrade with php7+ - I assume you're still on 5.6.

**Comment by molnarti** [comment]
sorry, i am stupid. i really forgot my password. and yes, i am on PHP 5.6., using it via DietPi. please erease/close the issue and apologies for bothering.

**Comment by ChristophWurst** [comment]
No worries. Great to hear you can log in again 😀
