### ISSUE TITLE
App does not prompt for two factor key

### ISSUE THREAD

**Issue by Luticus** [nextcloud/twofactor_totp#169]
When I activate the app and configure 2 factor in my personal settings and then log out, the app does not show up and prompt me for my 2 factor key.  Instead it just uses the regular login prompt anyway.

I use an LDAP account and have the jsxc xmpp chat app enabled which also hooks into the login process.  I've tried disabling the jsxc xmpp chat app and I still have the same issue.  Any ideas what I could try next?  I cannot disable LDAP as almost all users authenticate that way now.

**Comment by ChristophWurst** [comment]
Hi,

which version of Nextcloud are you using? What are the steps to reproduce this? Did you see the QR code when enabling the factor and a confirmation that it has been enabled?

**Comment by ChristophWurst** [comment]
Could also be that you disabled 2FA in general by using the CLI. In that case you can re-enable it with `php occ twofactorauth:enable <uid>`.

**Comment by Luticus** [comment]
I'm using the latest stable version of nextcloud 11.0.3 
Basically I enable the 2fa app and then go to my profile page where I set up a 2fa key.
Yes, I see the QR code and even scanned it with google auth.  
And I'm pretty sure it confirms that it's enabled.

I will definitely try your suggestion of running the occ command and see where that goes.  I'll let you know if it fixes the problem or not.

**Comment by Luticus** [comment]
That in fact worked!  Thank you very much for the help!
