### ISSUE TITLE
Enable twofactor_totp for the webapp only (not for the client)

### ISSUE THREAD

**Issue by me88** [nextcloud/twofactor_totp#170]
Hello 

I installed two factor totp.

I can use two factor auth with a web browser. Nevertheless, my client does not work anymore (client not connected). 

**My question : is there a way to enable two factor totp with the web version only (and not with my client)?**

Justification: I have a home PC with a trusted connection so I don't need two factor auth. Nevertheless, as I sometimes access to my nextcloud from other machines via the webrowser, I want to add extra security.

**Comment by rigrig** [comment]
There is no way to only enable two-factor authentication for the web interface, but if you go to **Personal settings  > App passwords** (`settings/personal#apppasswords`), you can create separate passcodes that give an app or device permissions to access your account.
If you set up your client to use one of those, it doesn't need two-factor authentication.

**Comment by me88** [comment]
OK thanks
