### ISSUE TITLE
Disabling 2FA for a specified User if sudo-command is not allowed

### ISSUE THREAD

**Issue by cebolina** [nextcloud/twofactor_totp#172]
[https://docs.nextcloud.com/server/10/admin_manual/configuration_server/occ_command.html#two-factor-authentication](url)
...but how can I disable 2FA for a specified User, if my Hoster (in my case all-inkl.com) do not allow sudo-Command via ssh?

**Comment by ChristophWurst** [comment]
Hi @cebolina,

unfortunately, there is currently no ways to do that via the web interface. But to be precise, are you just unable to use `sudo` or is there no ssh at all?

In any case, this would be an enhancement for the Nextcloud server and its web gui. This is somewhat related to https://github.com/nextcloud/server/issues/2348. Could you please create a new ticket in the server repository? Thanks!

**Comment by ChristophWurst** [comment]
> ssh is not the Problem. But indeed my hoster all-inkl.com does not allow to use sudo.

I see. Is the ssh user you log into your server the owner of your webserver's files? The `sudo` prefix in the docs is only meant to run the command as non-privileged user instead of root because that could otherwise cause permission problems.

If that's the case, run
```
php occ twofactor:disable <username>
```

**Comment by cebolina** [comment]
First of all: Thank you for helping a DAU like me!
1. I open a MAC-Terminal-Window
2. I log in with my ssh-login from all-inkl.com
3. I can see all my files and directories with 'dir' (like FTP)
4. I change Directory to my nextcloud-installation
5. With 'dir' I see all files/directories in my NC-Installation like this
/www/htdocs/w0012345/cloud/cloud$
drwxr-xr-x 44 ssh-w0012345 w0012345 4,0K <date> apps

In which Directory do I have to do: php occ twofactor:disable <username> ?

**Comment by ChristophWurst** [comment]
> In which Directory do I have to do: php occ twofactor:disable

In the root directory of your Nextcloud installation. I can only guess, but `/www/htdocs/w0012345/cloud/cloud` could be that directory. You can check by running `ls` or `dir` in the directory, you should see a file called `occ`.

**Comment by cebolina** [comment]
I see:
-rw-r--r-- 1 ssh-w0012345 w0012345 283 Apr 25 07:45 occ
I run:
php occ twofactor:disable username

Tataaa - it works! The User can login with Username and Password (no 2FA)

Thank you for your Patience. You can close this issue.

**Comment by ChristophWurst** [comment]
> Tataaa - it works! The User can login with Username and Password (no 2FA)
> 
> Thank you for your Patience. You can close this issue.

Great to hear that! You're welcome :)
