### ISSUE TITLE
Display glitch in NC 12, at least in german localisation

### ISSUE THREAD

**Issue by nursoda** [nextcloud/twofactor_totp#173]
After upgrading to NC 12, TOTP screen looks like this:
![totp-login-screen-in-nc-12](https://cloud.githubusercontent.com/assets/8425483/25974027/fa0aad32-36a6-11e7-8fed-ae373ac46d76.png)

**Comment by ChristophWurst** [comment]
What's the problem here? The button layout? If yes, this is a duplicate of https://github.com/nextcloud/server/issues/4298 :)

**Comment by nursoda** [comment]
Yes, the layout. text within the button wraps. OK, closed in favor of nextcloud/server#4298 .
