### ISSUE TITLE
Logging says login failed when using TOTP

### ISSUE THREAD

**Issue by contribguy** [nextcloud/twofactor_totp#176]
Hi!

When I log in to Nextcloud using the TOTP feature the log states there was a failed login attempt, even though I had no trouble logging in at all.

This happens when I'm logging in using the email-address specified in my account settings only. The error appears whether I'm logging in from local subnet or from outside.

Raw log output is found below.
```
{"reqId":"O2wkLSIXy8YRNWBcNDgL","remoteAddr":"***REMOVED SENSITIVE VALUE***","app":"core","message":"Login failed: '***REMOVED SENSITIVE VALUE***' (Remote IP: '***REMOVED SENSITIVE VALUE***')","level":2,"time":"2017-05-17T19:02:58+00:00","method":"POST","url":"\/index.php\/login","user":"--","version":"11.0.3.2"}
```

### Steps to reproduce
1. Create a new user in your Nextcloud instance and assign it to an email address.
2. Enable TOTP for that user.
3. Log out and back in using the email address.
4. Now you should have a "Login failed"-entry in the logfile.

### Expected behaviour
Only "real" failed login attempt should be listed in the log-file.

### Actual behaviour
The logfile states there was a failed login-attempt when I try to login using my accounts assigned email-address with TOTP-authentication.

### Server configuration
**Operating system**: Linux CLOUDSRV01 4.9.24-v7+ #993 SMP Wed Apr 26 18:01:23 BST 2017 armv7l

**Web server:** Apache (apache2handler)

**Database:** mysql 5.5.54

**PHP version:** 5.6.30-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, curl, gd, json, mcrypt, mysql, mysqli, pdo_mysql, readline, mhash, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-11.0.3.zip

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>

Enabled:
 - activity: 2.4.1
 - apporder: 0.3.3
 - comments: 1.1.0
 - dav: 1.1.1
 - direct_menu: 0.10.2
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - twofactor_totp: 1.1.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_retention
 - templateeditor
 - user_external
 - user_ldap
 - user_saml

</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocric2d3rz8a",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/nxcdata\/drive0\/c0",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "c0_nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "noreply",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Operating system:** Windows 7

**Comment by ChristophWurst** [comment]
Hi and thanks for reporting.

This has been fixed for Nextcloud 12 by https://github.com/nextcloud/server/pull/3043 😉
