### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by valir** [nextcloud/twofactor_totp#178]
Yesterday I activated TOTP on my cloud instance. It initially worked.
Today I come back wanting to upload stuff to it and it won't let me in.

From the screen shot, I understand I should see something like in the screenshot "enter_challenge.png". Instead, I'm presented to old, password login screen. I tried both my old password and the TOTP tokens without success.

Let's find-out what's wrong here.

nextcloud version: 12.0.0.5
system: fedora 24

Log entry I see on the server nextcloud.log when attempting log-in:

{"reqId":"60wY2WUJICuN3mioHrqB","level":2,"time":"2017-07-08T08:16:10+00:00","remoteAddr":"78.97.233.236","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=valentin","message":"Login failed: 'valentin' (Remote IP: '78.97.xx.xx')","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.29"}

**Comment by ChristophWurst** [comment]
> From the screen shot, I understand I should see something like in the screenshot "enter_challenge.png". Instead, I'm presented to old, password login screen. I tried both my old password and the TOTP tokens without success.

Yes, you still have to enter your password. Right after that you're asked to enter your OTP token.

**Comment by valir** [comment]
OK, I understand, and if I think about it twice, this is how it should work. However, it won't work. My initial password ~~is~~/was rejected. I say "was" because I just tried again and now it works.

Maybe the application I use is not that precise? I got one from the f-droit market named "android token"

**Comment by ChristophWurst** [comment]
yeah that could be the problem. A little time drift between the server clock and your phone's can cause invalid OTPs. Make sure they are in sync.
