### ISSUE TITLE
Fix builds

### ISSUE THREAD

**Issue by Hanzei** [nextcloud/twofactor_totp#179]
See discussion here https://github.com/nextcloud/twofactor_u2f/issues/58#issuecomment-314378402

**Comment by Hanzei** [comment]
Is there a reason we test PHP_COVERAGE against pgsql and run sauce against mysql?

**Comment by ChristophWurst** [comment]
> Is there a reason we test php coverage against pgsql (https://github.com/nextcloud/twofactor_totp/blob/master/.travis.yml#L96) and run sauce against mysql (https://github.com/nextcloud/twofactor_totp/blob/master/.travis.yml#L100)?

Yes, one reason is to split long-running build jobs into multiple to reduce the overall time needed to check a commit/PR. Hence one of the jobs does the slow coverage (phpunit is slower when xdebug is enabled) and another one runs slow integration tests. Does that make sense? :)

**Comment by Hanzei** [comment]
This makes perfect sense ;). But my questions was about the choice of the database. Normally sqlite is used, but for the special build runs pgsql and mysql are used. Why?

**Comment by ChristophWurst** [comment]
> This makes perfect sense ;). But my questions was about the choice of the database. Normally sqlite is used, but for the special build runs pgsql and mysql are used. Why?

¯\_(ツ)_/¯ dunno, I don't remember, sorry.

**Comment by Hanzei** [comment]
Fixed with #187
