### ISSUE TITLE
[Suggestion] When entering the last digit, automatically submit and check (saves users' enter click) 

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/twofactor_totp#180]
[Suggestion] When entering the last digit, automatically submit and check (saves users' enter click) 

* originally filed as https://github.com/nextcloud/server/issues/2709

Please allow me to suggest, if possible, to implement

#### Suggestion

* when user enters the last (i.e. the 6th) digit, that then automatically the entered auth code is submitted.

This saves one click (only disadvantage: a correction of the last digit will be impossible).

**Comment by Wikinaut** [comment]
*ping*

**Comment by haraldkoch** [comment]
This goes against the general user expectation that nothing happens until one hits "Enter" or clicks a submit button. It's not good UX, in my opinion. I have a similar dislike of split fields that automatically advance, especially when they also make it difficult or impossible to correct typos.

**Comment by Wikinaut** [comment]
Let's see what the "general user" has to say.

**Comment by ChristophWurst** [comment]
I'm also a bit on the fence with this "enhancement". A compromise would be to have a timeout of a few seconds that starts once six digits have been entered and auto-submits if no further changes are made.

From a technical PoV we'd need a new webpack entry point for the challenge page (very similar to what we use for the u2f app). While touching this, I'd migrate the challenge template to Vue, but that is of course optional.

**Comment by Wikinaut** [comment]
@ChristophWurst as I would like to implement it here for my servers, pls. simply point me a little where to apply such a patch. Thank you. I personally hate superfluous clicks like the Enter key and like responsive servers and services.

**Comment by Wikinaut** [comment]
Because my proposal does not find a positive, but only negative response so far, I withdraw it. Basta.
