### ISSUE TITLE
[suggestion] Generate Backup codes using admin panel

### ISSUE THREAD

**Issue by insyria** [nextcloud/twofactor_totp#182]
Issue:
User didn't generate Backup codes, and the phone is not working.

Solution:
Admin can generate codes for the user.

**Comment by ChristophWurst** [comment]
Hi,

that could be a nice enhancement. From a development perspective, a CLI command to generate those codes would require the least effort. Could you please file an enhancement issue at the server repo? Backup codes are a generic feature for any two-factor provider, not only the TOTP one. Thanks!
