### ISSUE TITLE
TOTP bypass whitelist

### ISSUE THREAD

**Issue by richardtector** [nextcloud/twofactor_totp#183]
In some cases a user may trust certain IP addresses (perhaps static IP address at home) and would prefer not to go through the two-factor auth process and rely on password alone.

Would it be feasible to add the ability to include IP addresses/ranges to the appropriate section on a user's configuration page?

Thanks

**Comment by richardtector** [comment]
Ah - I didn't do my homework. This is already covered by https://github.com/nextcloud/server/issues/2035

Feel free to close this.

**Comment by rigrig** [comment]
Thanks for finding and linking to the existing issue!
