### ISSUE TITLE
Unable to authenticate with totp

### ISSUE THREAD

**Issue by K1N62** [nextcloud/twofactor_totp#185]
After upgrading to 12.0.1 from 12.0.0 the totp stopped working. I was not able to log in to the web interface with the error "Error verifying two-factor authentication". I temporarily disabled totp in order to log in, now I'm trying to reactivate totp but after registering the new Authentication code with google authenticator I'm unable to verify it with the error "could not verify your key, please try again". There is no additional information in the logs. 

TOTP version: 1.3.0
Nextcloud version: 12.0.1

**Comment by XTREEMMAK** [comment]
I am also not able to initially get this working. I keep getting an unable to verify error. Turned it off for now.

**Comment by ChristophWurst** [comment]
Hi,

has anybody of you checked whether the clocks of your server on the one on your phone are in sync? The OTP algorithm uses the current time to verify a code is valid, hence the verification fails if clocks are out of sync.

**Comment by K1N62** [comment]
The server is synced with NTP and there is about 2 min time difference between the phone and the server. The phone uses network time and is in sync, also the authenticator app is in sync with googles time servers.

**Comment by ChristophWurst** [comment]
> The server is synced with NTP and there is about 2 min time difference between the phone and the server. The phone uses network time and is in sync, also the authenticator app is in sync with googles time servers.

Interesting. Could you try to temporarily set your phone's clock to manual mode and sync it with your server? Then we can make sure this is the actual problem.
I'm curious why those two synchronized systems aren't in sync compared to each other. Maybe one of the time servers is out of sync.

**Comment by K1N62** [comment]
Setting the time manually works, I guess the time was the issue all along. I am also curious why the time was not synced, I manually force synced both the server and the phone just to be sure. I have now changed the NTP server to a server located in my country instead of the ubuntu default, hopefully this will prevent this issue in the future.

**Comment by ChristophWurst** [comment]
Okay, thanks for your feedback.

As a future enhancement we could show the server time whenever the verification fails to allow users to self-check whether their clocks are in sync or not.

**Comment by K1N62** [comment]
That would be useful. Thanks for the support :)

**Comment by sunjam** [comment]
Is this on the roadmap as a feature?

**Comment by ChristophWurst** [comment]
> Is this on the roadmap as a feature?

Not yet. Would you be interested in contributing?

**Comment by sunjam** [comment]
I'm honestly now sure on how to program this, but I would be interested.
