### ISSUE TITLE
Unable to sync using desktop client for both Mac and Windows

### ISSUE THREAD

**Issue by Daiyosg** [nextcloud/twofactor_totp#191]
Hi there,

Apologise if this issue had been rectify earlier on, yet due to i am still very new to this, i was googling and cant find a detail steps in overcoming the "fail to sync", after activating TOTP.

Hence, really appreciate if someone could advise or direct me to a site where i can follow steps to overcome this "fail to sync" issues.

Thanks & Regards,

Daiyosg

**Comment by ChristophWurst** [comment]
Hi,

you have to use app passwords for your client to be able to use them in combination with two-factor auth. For more info see the documentation or ask for help on the nextcloud forum. Thanks :)
