### ISSUE TITLE
BUG: each change in Setting requires authentication which doesn't work

### ISSUE THREAD

**Issue by devmoibrahim** [nextcloud/twofactor_totp#194]
I am using NextCloud 12.0 on shared host,
each time i need to change anything in the settings like enabling app, adding my email to the profile, nextcloud pops up a window for authentication. I enter the correct password, but it stills ask me for the password again and again.

**Comment by ChristophWurst** [comment]
Hi,

this password protection is part of the Nextcloud server. Thus, please file a ticket at https://github.com/nextcloud/server/issues/new and make sure you provide the information the template is asking you for. It's also possible that someone already files this bug, so first check out https://github.com/nextcloud/server/issues and try to find an existing ticket.

Thanks.
