### ISSUE TITLE
Two factor broken after droplet resize

### ISSUE THREAD

**Issue by martinchodev** [nextcloud/twofactor_totp#198]
Hello, I have an instance of Nextcloud 11.0.5 on a VPS in DigitalOcean.
Yesterday I resized the droplet so the amount of RAM has doubled, and the SSD also changed by +10GB.
Today, I've been trying to log in via web and the OTP codes just don't work. This happens with 2 accounts, mine and the administrators account too.
I have tried in different browsers but no luck.
I don't have the recovery codes with me, so I will try that later today.

I wanted to know if resizing the droplet can affect the generation of the OTP in this way, or is it just coincidence?

Thank you.

**Comment by martinchodev** [comment]
I have managed to access the accounts by disabling the two-factor plugin with the occ command.
Still, I would like to know if the resizing of the droplet could have caused this.

**Comment by ChristophWurst** [comment]
> I wanted to know if resizing the droplet can affect the generation of the OTP in this way, or is it just coincidence?

I bet it's a coincidence and the server clock is out of sync. Syn it against a NTP and compare the time on your phone and the one on your server. I'm pretty sure there's a diff of more than 30secs 😉

**Comment by ChristophWurst** [comment]
No feedback -> closing.
