### ISSUE TITLE
Access to Api

### ISSUE THREAD

**Issue by ssoftS** [nextcloud/twofactor_totp#199]
Hey,
i have enabled the 2fa-app and created the AppPins.
From my desktop-app (develop) i can't access via username & password, but with AppPins.
That is correct.

BUT: when i create a query to `/ocs/v1/person/check` then i must have the password instead AppPin.

According to the app-documentation, the logon must over the username+app-pin respectively.
Is this a security-bug?

**Comment by ChristophWurst** [comment]
> BUT: when i create a query to /ocs/v1/person/check then i must have the password instead AppPin.

What are you trying to do?

> Is this a security-bug?

cc @LukasReschke

**Comment by ssoftS** [comment]
over this query i will check the correct login-data (username&password/apppin).
This confused me, when the docu something else says.
bruteforce-attacks are easier, because the password-length... etc.

**Comment by ChristophWurst** [comment]
I see. So this has nothing to so with TOTP specifically, but you need general advice for building your app. So please check help.nextcloud.com for that or join the IRC channel #nextcloud-dev. I don't know the answer to your problem as I'm not familiar with the public OCS API of Nextcloud, sorry.

**Comment by ssoftS** [comment]
i have no problem with my desktop-app, but this is a security-risc.
the 2fa-app does not go deep enough in nextcloud.
