### ISSUE TITLE
Android api login erroring

### ISSUE THREAD

**Issue by DrTechdom** [nextcloud/twofactor_totp#201]
I am trying to login to nextcloud with "Two Factor TOTP Provider", after entering my username and the token I am given an "http error 401".
two factor: 1.3.1 (up-to-date)
nextcloud: 12.0.3 (up-to-date)
android: up-to-date

**Comment by ChristophWurst** [comment]
Is it the exact same username you've used to log into the web interface?

**Comment by DrTechdom** [comment]
yes

**Comment by ChristophWurst** [comment]
On the login screen, what did you use as password? What are you trying to authenticate? Your browser or the official Nextcloud app?

**Comment by ChristophWurst** [comment]
Closing this now as I didn't get any answers to my questions.
