### ISSUE TITLE
Backlink to list of 2FAs.

### ISSUE THREAD

**Issue by My1** [nextcloud/twofactor_totp#202]
it is kinda annoying when you select a 2FA provider and then realize you cant use it (Phone has no battery left for example) that your only choices are backup code and cancel login.

in my opinion there should be a button that just brings you back to the list of challenges, so you can just select another.

also why does the Backup code button come there? wouldnt it make more sense if that would be on the 2FA selection screen?

**Comment by ChristophWurst** [comment]
Those are two very valid points. May I ask you to raise this as a ticket in the server repo https://github.com/nextcloud/server/issues/new? Thanks a lot

**Comment by ChristophWurst** [comment]
(Backup codes and the general 2FA workflow are handled by the NC server)
