### ISSUE TITLE
Get a list of users who do not enable TOTP

### ISSUE THREAD

**Issue by Huarong** [nextcloud/twofactor_totp#205]
We wish the feature of #41 .

But at least the administrator should know a list of users who do not enable TOTP.

**Comment by ChristophWurst** [comment]
> We wish the feature of #41 .

No need to file a duplicate ticket on purpose. If you *whish* to have this feature, maybe you could help implement it if you're a developer. Otherwise there's always the option to find someone else who can help you with this.

**Comment by r2evans** [comment]
FYI, list users can be done, albeit painfully. My nc is in a docker instance, so 

```
php occ user:list \
  | sed -E 's/^ *- ([^ ]+):.*/\1/g' \
  | while read U ; do  php occ twofactorauth:state $U ; done \
  | grep Two-factor
```
