### ISSUE TITLE
Check if a user has TOTP active

### ISSUE THREAD

**Issue by maximelovino** [nextcloud/twofactor_totp#206]
Hi,
I'm looking for a way to check if a user has activated TOTP for his account. I know that with the occ command you can enable/disable TOTP for a user but I haven't find a way to know if the user has activated it by himself or not. (Without checking in the DB if the user has a TOTP secret, because I only have access to ssh at the moment).

Thank you in advance for your help

**Comment by ChristophWurst** [comment]
Hi,

are you familiar with PHP? I could guide you on how to add a CLI command to check that.

**Comment by maximelovino** [comment]
Yes, I am

**Comment by ChristophWurst** [comment]
Great. Here you can see an example command: https://github.com/nextcloud/activity/tree/master/lib/Command

The registration is done via info.xml: https://github.com/nextcloud/activity/blob/master/appinfo/info.xml#L62-L64

**Comment by maximelovino** [comment]
Okay, I will check that one day perhaps...Don't have much time at the moment.

Thank you

**Comment by ChristophWurst** [comment]
I'll consider it.

I'm closing this ticket due to lack of activity and because the feature should be implemented in the [Nextcloud server](https://github.com/nextcloud/server) instead.
