### ISSUE TITLE
Nextcloud 13 support

### ISSUE THREAD

**Issue by Varbin** [nextcloud/twofactor_totp#207]
Currently this app does not support Nextcloud 13 (beta) yet. I'm currently testing the Nextcloud beta, so an official (testing) release would be nice.

Thanks in advance.

Edit: Ah, sorry missed the pull request #181 .

**Comment by ChristophWurst** [comment]
I'm working on that: https://github.com/orgs/nextcloud/projects/4#card-5870355 - but thanks for your feedback and for testing the beta 😉

**Comment by Sp1l** [comment]
@Varbin the current release works OK for me when I bumb the version in `appinfo/info.php`. I haven't found an issue there yet for users that have already setup TOTP. I haven't tested adding TOTP to a user yet.

**Comment by ChristophWurst** [comment]
Thanks for testing. There have been a few changes since the last release though: https://github.com/nextcloud/twofactor_totp/compare/1.3.1...master

I'll probably get to updating this app on Monday or Tuesday. Once it's ready, may I ask you to give it a quick test? That would be awesome.

**Comment by Varbin** [comment]
Yes I'll try. 
I got the current  master to work (registering a user, login).  An official testing release would still be nice (which can be installed through appstore.

**Comment by tacruc** [comment]
Tested the Version from the app store on NC13 Beta 1 everything seems to work.

- [ ] Enabled App
- [ ] Enabled App for a new User
- [ ] Loged in with new 2FA device

**Comment by tacruc** [comment]
I had download the app from befor the update. Just changed the maximal Version in the info.xml. 
Thats the one change I forgot.

**Comment by ChristophWurst** [comment]
> I had download the app from befor the update. Just changed the maximal Version in the info.xml.
> Thats the one change I forgot.

Okidoke, thanks for testing. There are a few changes to the way the settings page is registered that are new in nc13. I'm working on that now. Should be compatible already though.

**Comment by ChristophWurst** [comment]
Party time! Here's a preview build: https://github.com/nextcloud/twofactor_totp/pull/210

Please help me test this package on Nextcloud 13 (won't work on nc12) and report back whether it was successful or not. Thanks a lot 😉

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/twofactor_totp/pull/210
