### ISSUE TITLE
Request: TOTP Federation

### ISSUE THREAD

**Issue by sunjam** [nextcloud/twofactor_totp#208]
I'm interested in federation of TOTP between multiple nextcloud instances so they can be activated simulatenously from the same Google Authenticator code. I know you all have a lot on your plate, but let me know if this has been considered. :)

**Comment by ChristophWurst** [comment]
> but let me know if this has been considered.

It hasn't 😉

**Comment by GoetheG** [comment]
This is an interesting function which I would like to have as well.

**Comment by ChristophWurst** [comment]
> This is an interesting function which I would like to have as well.

Pull request are welcome at any time!

**Comment by rullzer** [comment]
You should not reuse TOTP secrets. Just like you should not reuse passwords.
Just setup TOTP properly on each instance with its own secret.
