### ISSUE TITLE
Enable both username/password login and TOTP

### ISSUE THREAD

**Issue by magicsunday** [nextcloud/twofactor_totp#220]
Why its not possible to login with username/password combination and afterwards running the TOTP auth? Isn't this implemented?

**Comment by ChristophWurst** [comment]
I'm not sure if I understand your report. Isn't hat exactly what the app does right now? Could you maybe write down expected vs. actual steps so that it's more clear? Thanks.

**Comment by magicsunday** [comment]
Oh sorry.

I would have expected in a two-factor authentication (I have seen so far for example on various Bitcoin exchanges) that I enter as the 1st factor my username / password and as a second factor the one-time password (TOTP). Currently you only have to enter the one-time password, so in my understandung this is not a true two factor authentication.

**Comment by magicsunday** [comment]
Uh my fault. In my first test I only got the TOTP not the user/pass dialog, Maybe a browser cache problem.
