### ISSUE TITLE
longevity of Backup-Codes

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/twofactor_totp#244]
maybe just a question...
but shouldn't the Backup-Codes be cleared/deleted after an user disables TOTP?

in the database they are still present, also for users which were completely deleted ages ago.

i'm not sure if this may even become a security issue, especially if a user enables TOTP again...

**Comment by ChristophWurst** [comment]
Hey,

backup codes are part of the nextcloud [server](https://github.com/nextcloud/server), not this app. Currently there is no mechanism to detect when users disable their 2FA app.

We could clean up backup codes of deleted users though. Would you mind filing a ticket at the server repo for that?

Thanks for your feedback

**Comment by DJCrashdummy** [comment]
thanks for your quick reply! already done: https://github.com/nextcloud/server/issues/9036

sorry for bothering you with this. - i just use TOTP and so i thought it is a feature of this app.

**Comment by ChristophWurst** [comment]
> thanks for your quick reply! already done: nextcloud/server#9036

Thanks! :rocket: 

> sorry for bothering you with this. - i just use TOTP and so i thought it is a feature of this app.

No worries :wink:
