### ISSUE TITLE
Can't login with Gnome 3 online accounts

### ISSUE THREAD

**Issue by RDominique** [nextcloud/twofactor_totp#246]
If I enable TOTP, I can't access the files from the integrated nextcloud plugin in Gnome 3.
Error message is 'http-error: Unauthorized'
Also if I want to connect manually with davs://nextcloud.crowdcloud.be/remote.php/webdav/ I get the same error.
Calendar and contacts works like a charm. So its only the files I can't get access to.
All other clients (Android, Windows) works fine with TOTP enabled.   
I could enter a bug report with Gnome but if I disable TOTP, accessing the files works fine.   
If the Gnome guys should change their plugin somehow, please help me assemble the correct info to communicate to the Gnome programmers.
Thanks in advance.

**Comment by ChristophWurst** [comment]
Hey,

since you're using TOTP and thuse *two factor authentication*, Gnome is not allowed to access your Nextcloud data with the login password. You have to use an app password instead: https://docs.nextcloud.com/server/13/user_manual/session_management.html#managing-devices.

**Comment by ChristophWurst** [comment]
Gnome online accounts work fine for me. Could you maybe report this to Gnome instead? Have you checked you nextcloud.log when the login errors occur?

**Comment by joho1001** [comment]
to fix this, 
go to nextcloud settings->security,
add a new App-Password for e.g. "gvfs".

you will have to enter a username and nextcloud will provide a reasonable password.
use this username and password combination for gnome online accounts nextcloud.

**Comment by tillhanke** [comment]
I have just experienced a simmilar issue with GDM3. I use TOTP and generated a app password for gnome. Login worked just fine, and I can see my calendar as well as all contacts. But when I try to open the files I get a Error:
````
Unable to access "user@mynextcloud.com"
HTTP Error: Unauthorized
````
