### ISSUE TITLE
How to manually inactivate plugin

### ISSUE THREAD

**Issue by kevdogg** [nextcloud/twofactor_totp#248]
I'm running nextcloud on my own box at home and had activated the totp plugin from inside the app.  Unfortunately the totp app on my phone was lost when my phone pretty much went belly up and died.  I don't have any manual codes saved but have root access to the server.  Is there a way in any of the config files to manually turn off or deactivate this plugin? Thanks.

**Comment by ChristophWurst** [comment]
> Sorry to waste your time.

No worries. Great to hear that you could resolve the issue :wink:
