### ISSUE TITLE
Unable to enable totp and NC 13.0.4

### ISSUE THREAD

**Issue by papanito** [nextcloud/twofactor_totp#253]
I recently had a crash on my server so I had to do a db restore. Since then totp is not working anymore. So I had disabled and tried to enable it again. I get a QR Code which I can successfully scan, but unfortunately the code is not accepted. I don't find any indication in the log file though
### Steps to reproduce
1. Go to /settings/user/security
1. Disable totp
1. Enable totp [x]
1. Scan code with Google Authenticator
1. Enter Authentication code in NC and click "Verify"

### Expected behaviour
Authentication code is accepted and totp is enabled

### Actual behaviour
Error message "Could not verify your key. Please try again" and totp is not enabled

### Server configuration

**Operating system**:
Linux proxmox 4.13.16-2-pve  (Debian 9)
**Web server:**
nginx 1.10.3-1+deb9u1
**Database:**
mariadb-server 10.1.26-0+deb9u1 

**PHP version:**
7.0.27-0+deb9u1 

**Version:** (see admin page)
13.0.4

**Updated from an older version or fresh install:**
Issue on 13.0.3. Did upgrade then to 13.0.4 with the same outcome

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.3
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - encryption: 2.0.0
  - external: 3.0.3
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - phonetrack: 0.2.8
  - provisioning_api: 1.3.0
  - richdocuments: 2.0.8
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.2
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.myhost.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc.myhost.com",
        "dbtype": "mysql",
        "version": "13.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "updater.release.channel": "beta",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 0,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

#### Client configuration
**Browser:**
Firefox 60.0.1
**Operating system:**
Linux

##### Web server error log
```
nothing relevant in time during enabling of totp
```

##### Server log (data/nextcloud.log)
```
nothing relevant in time during enabling of totp
```

##### Browser log
```
nothing relevant
```

**Comment by ChristophWurst** [comment]
> I recently had a crash on my server so I had to do a db restore. Since then totp is not working anymore.

Could you please check the time on your server and your phone. Are they in sync?

**Comment by ChristophWurst** [comment]
> Server log (data/nextcloud.log)
> 
> nothing relevant in time during enabling of totp

Is there *anything* logged during the login attempt? Please set the log level to `debug` and try again.

**Comment by papanito** [comment]
Yep, shystem time was 3  mins behind. Seems that my ISP blocked external ntp servers. Fixed it now all is fine

**Comment by ChristophWurst** [comment]
Great!
