### ISSUE TITLE
I have recently got this code integrity error /warning

### ISSUE THREAD

**Issue by sign-out** [nextcloud/twofactor_totp#255]
I have recently got this code integrity error /warning. i run next could from the snap so I am unsure how to resolve and or restore the apps integrity  as the snap is read only (probably something to bring up with the team for that). I thought I should let you know of it as i don't know how it happened or why  let me know if you have any questions or need any more information 

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- twofactor_rcdevsopenotp
	- FILE_MISSING
		- l10n/.tx/config

Raw output
==========
Array
(
    [twofactor_rcdevsopenotp] => Array
        (
            [FILE_MISSING] => Array
                (
                    [l10n/.tx/config] => Array
                        (
                            [expected] => 5ad14bb93e25fd93ebbd96e1e995367db065d11953f0c3ac707962098956f1a9f5534a7dcceb834ebfb4a6b3edd7f6a8c6cbddd01c052bbb61fe951c779f2fca
                            [current] => 
                        )

                )

        )

)

**Comment by ChristophWurst** [comment]
> twofactor_rcdevsopenotp

Please report that to the respective app. Sounds like you are using this: https://github.com/rcdevs/openotp_authentication_nextcloud
