### ISSUE TITLE
Upgrading from Nextcloud 13.0.4 to 13.0.5 fails code integrity check

### ISSUE THREAD

**Issue by whisperdancer** [nextcloud/twofactor_totp#261]
### Steps to reproduce
1.  Simply perform the web based update on nextcloud
2.
3.

### Expected behavior
It should update without issues.

### Actual behavior
Update succeeded, but failed integrity check. And only with 2FA app
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- twofactor_rcdevsopenotp
	- FILE_MISSING
		- l10n/.tx/config

Raw output
==========
Array
(
    [twofactor_rcdevsopenotp] => Array
        (
            [FILE_MISSING] => Array
                (
                    [l10n/.tx/config] => Array
                        (
                            [expected] => 5ad14bb93e25fd93ebbd96e1e995367db065d11953f0c3ac707962098956f1a9f5534a7dcceb834ebfb4a6b3edd7f6a8c6cbddd01c052bbb61fe951c779f2fca
                            [current] => 
                        )
                )
        )
)

### Server configuration

**Operating system**: 
Raspbian Stretch 9.4

**Web server:** 
nginx version: nginx/1.10.3

**Database:**
Marion DB latest Version

**PHP version:**
7.0

**Version:** (see admin page)

**Updated from an older version or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:**
Firefox 64.0.1

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by ChristophWurst** [comment]
Dup of #255, #260.
