### ISSUE TITLE
unlock issue #100

### ISSUE THREAD

**Issue by tessus** [nextcloud/twofactor_totp#273]
@ChristophWurst You asked to move the discussion to #100.

We would have done that in the first place, if it hadn't been locked. There is no way to add any comments to #100. I would have told you that in #245, but you locked that topic too.

Can you please stop locking issues? Is this a kindergarden?

**Comment by ChristophWurst** [comment]
Could you please check again? https://github.com/nextcloud/twofactor_totp/issues/100 definitely *isn't* locked.

> Can you please stop locking issues? Is this a kindergarden?

It's a duplicate and I've clearly stated that.

**Comment by ChristophWurst** [comment]
You even added reactions to that ticket :see_no_evil: You couldn't have done that if it were locked.

**Comment by tessus** [comment]
I know that it's a duplicate and it's totally fine to lock an issue, if people are ignoring this.

However, if I can't add comments to the other one, I do not have a choice. Also there's apparently a difference between adding reactions and adding a comment.
Here's my proof:

<img width="850" alt="screen shot 2018-09-14 at 03 11 36" src="https://user-images.githubusercontent.com/223439/45535384-485bfe80-b7cc-11e8-96be-a0c2efef17d2.png">

**Comment by ChristophWurst** [comment]
Alright, now I'm confused too. This ticket isn't locked on my end, at least that's what GitHub shows me on the UI. Let me try to lock and unlock.

**Comment by ChristophWurst** [comment]
Please check again. Otherwise I'd suggest to just start a fresh ticket.

Sorry for the confusion.

**Comment by tessus** [comment]
Nope, still the same problem.

**Comment by ChristophWurst** [comment]
@tessus @sindastra please open a new ticket to discuss https://github.com/nextcloud/twofactor_totp/issues/100. Apparently GitHub support won't help me in unlocking the original issue for @tessus and I can't figure out any other way to continue discussion there if one person is unable to comment.

**Comment by ChristophWurst** [comment]
-> #245
