### ISSUE TITLE
Slow load of OTP request code after standard login

### ISSUE THREAD

**Issue by Boia11** [nextcloud/twofactor_totp#275]
### Steps to reproduce
1. Login with TOTP enable

### Expected behaviour
Fast request of OTP code

### Actual behaviour
Slow request of OTP code

### Server configuration

**Operating system**: Debian 9.5

**Web server:** Apache/2.4.25

**Database:** MariaDB 10.1.26

**PHP version:** 7.0.30

**Version:** 14.0.0

**Plugin Version:** 1.5.0

**Updated from an older version or fresh install:** from 13

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - admin_notifications: 1.0.2
  - announcementcenter: 3.3.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - deck: 0.4.1
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - metadata: 0.7.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - ransomware_protection: 1.2.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - socialsharing_email: 1.0.4
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - w2g2: 2.2.3
  - workflowengine: 1.4.0
Disabled:
  - checksum
  - encryption
  - files_antivirus
  - files_external
  - files_retention
  - files_snapshots
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.boiaeleven.tk"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.boiaeleven.tk",
        "dbtype": "mysql",
        "version": "14.0.0.19",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
#### Client configuration
**Browser:** Firefox 62.0.2 (64bit)

**Operating system:** Windows 10 (build 1803)

##### Browser log 

**Network log (HAR):** [twofactor_totp - issues - slow loading.txt](https://cloud.boiaeleven.tk/index.php/s/tsQZ5SmJA4Yz6gP)

**Comment by ChristophWurst** [comment]
Did you enter any wrong codes? There's a brute force protection in place that will slow down response times.

**Comment by Boia11** [comment]
> 
> 
> Did you enter any wrong codes? There's a brute force protection in place that will slow down response times.

Nope, it do all time with all account.
The sequences of request is repeat more times before compleate load of page and only after complete page loading the text box for insert OTP code is enable

**Comment by ChristophWurst** [comment]
Is that the only request that is slow?

Could you check for logged messages in `nextcloud.log` while you log into your instance?

**Comment by ChristophWurst** [comment]
Thank you for the logs.
I see lots of redirects to the 2FA screen – are you sure there is no brute force protection that slows down your instance?

**Comment by ChristophWurst** [comment]
Looks like the w2g2 app sends loads of requests that end up being redirected to the 2fa screen. Maybe that triggers the brute force protection.

The app must not send any requests to Nextcloud while the user is not fully logged in but it does https://github.com/newroco/W2G2/blob/5d7c845560c0e20d1154ed62b2141700017224d9/w2g2/appinfo/app.php#L18.

**Comment by Boia11** [comment]
> 
> 
> Looks like the w2g2 app sends loads of requests that end up being redirected to the 2fa screen. Maybe that triggers the brute force protection.
> 
> The app must not send any requests to Nextcloud while the user is not fully logged in but it does https://github.com/newroco/W2G2/blob/5d7c845560c0e20d1154ed62b2141700017224d9/w2g2/appinfo/app.php#L18.

You are the best....the problem is really W2G2 app.
After disable the OTP request is very fast.
Thanks!
Now I'll notice that at W2G2 developers

**Comment by ChristophWurst** [comment]
Perfect! :v:
