### ISSUE TITLE
Can't configure TOTP on master

### ISSUE THREAD

**Issue by schiessle** [nextcloud/twofactor_totp#297]
On the latest master for both server and the totp app I can't configure TOTP. That's how it looks like after a fresh installation:

![image](https://user-images.githubusercontent.com/1589737/47969606-587cb580-e07a-11e8-9297-dcf980d6f5e8.png)

**Comment by ChristophWurst** [comment]
What master? This app's master? Nextcloud server master? How did you install this app? Via a git clone or a packaged release?

**Comment by ChristophWurst** [comment]
Also, please check your browser's console for logged errors.

**Comment by ChristophWurst** [comment]
![bildschirmfoto von 2018-11-05 07-49-37](https://user-images.githubusercontent.com/1374172/47982257-63156a00-e0cf-11e8-9cff-25f8411c6a80.png)

Can't reproduce with latest server master and this app's master branch. Did you install php/js dependencies and run `npm run build`? (ref #278)

**Comment by schiessle** [comment]
both, server and this app are from git master.

In the JS console I have this two errors:

````
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
Loading failed for the <script> with source “http://localhost/master/apps/twofactor_totp/js/settings.js?v=d0b592ce-0”.
Loading failed for the <script> with source “http://localhost/master/core/vendor/zxcvbn/dist/zxcvbn.js”. security:1:1
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost/master/core/vendor/zxcvbn/dist/zxcvbn.js (“script-src”). 
````

Browser is Firefox 63.0.1

**Comment by schiessle** [comment]
OK, works now after I completed the setup instructions from the readme, sory for the noise
