### ISSUE TITLE
Android Logon (webdav) creates exception, login not possible.

### ISSUE THREAD

**Issue by styx-tdo** [nextcloud/twofactor_totp#331]
### Steps to reproduce
1. Enable TOTP on NC14 (latest patch)
2. Connect with nextcloud for Android
3. Error is shown to client - BEFORE password is entered

### Expected behaviour
Login should proceed and offer app password generation

### Actual behaviour
exception

### Server configuration

**Operating system**: Linux

**Web server:** NginX

**Database:** mySQL

**PHP version:** 7.2.9-1

**Version:** (see admin page)
1.5.0

**Updated from an older version or fresh install:**
upgrade

**List of activated apps:**
.. many?

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```  - accessibility: 1.0.1
  - admin_audit: 1.4.0
  - bookmarks: 0.14.2
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - caniupdate: 0.2.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.7
  - dashboard: 5.0.1
  - data_request: 1.1.0
  - dav: 1.6.0
  - deck: 0.5.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_automatedtagging: 1.4.0
  - files_downloadactivity: 1.3.0
  - files_external: 1.5.0
  - files_markdown: 2.0.5
  - files_mindmap: 0.0.10
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - flowupload: 0.0.8
  - gallery: 18.1.0
  - grauphel: 0.7.0
  - lookup_server_connector: 1.2.0
  - mindmaps: 0.1.0
  - nextcloud_announcements: 1.3.0
  - ocsms: 2.0.2
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - passwords: 2018.11.2
  - phonetrack: 0.3.8
  - provisioning_api: 1.4.0
  - qownnotesapi: 18.11.0
  - quota_warning: 1.3.0
  - ransomware_detection: 0.4.1
  - ransomware_protection: 1.2.0
  - scanner: 0.0.2
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.1
  - support: 1.0.0
  - survey_client: 1.2.0
  - tasks: 0.9.8
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_gateway: 0.11.0
  - twofactor_totp: 1.5.0
  - user_usage_report: 1.1.0
  - workflowengine: 1.4.0


**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.office-vienna.at",
            "cloud.office-vienna.at",
            "www.meinedaten.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "updatechecker": true,
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/cloud.office-vienna.at",
        "maintenance": false
    }

```

#### Client configuration
**Browser:** Android Client, new from playstore

**Operating system:**

##### Server log (data/nextcloud.log)

{"reqId":"JVXCxRNGaR7Dpeplkh24","level":0,"time":"2018-11-27T20:56:02+00:00","remoteAddr":"xxxxxx","user":"--","app":"webdav","method":"HEAD","url":"\/remote.php\/webdav\/","message":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured","Code":0,"Trace":[{"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.office-vienna.at\/remote.php\/webdav\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"autoRequireLogin":true,"__class__":"Sabre\\DAV\\Auth\\Plugin"},"beforeMethod"],[{"absoluteUrl":"https:\/\/cloud.office-vienna.at\/remote.php\/webdav\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",[{"absoluteUrl":"https:\/\/cloud.office-vienna.at\/remote.php\/webdav\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.office-vienna.at\/remote.php\/webdav\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":168,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/3.3.2","version":"14.0.3.0"}

{"reqId":"ExnnL7E6qrBWnlv24LGj","level":3,"time":"2018-11-27T20:56:03+00:00","remoteAddr":"xxxxx","user":"--","app":"index","method":"GET","url":"\/index.php\/login\/flow","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OC\\Core\\Controller\\ClientFlowLoginController! Class OCA\\OAuth2\\Db\\ClientMapper does not exist","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":119,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OC\\Core\\Controller\\ClientFlowLoginController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":451,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OC\\Core\\Controller\\ClientFlowLoginController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":424,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OC\\Core\\Controller\\ClientFlowLoginController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":105,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OC\\Core\\Controller\\ClientFlowLoginController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\ClientFlowLoginController","showAuthPickerPage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.ClientFlowLogin.showAuthPickerPage"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.ClientFlowLogin.showAuthPickerPage"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.ClientFlowLogin.showAuthPickerPage"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/login\/flow"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","Line":104,"CustomMessage":"--"},"userAgent":"xxx xxx-xxx","version":"14.0.3.0"}

##### Browser log
N/A - Android Nextcloud Client.

Login works flawless when TOTP is disabled or not active for the group.
i.e. - even if TOTP is NOT configured for this user, it prevents logon, as the error appears pre-auth

**Comment by tobiasKaminsky** [comment]
Not that I am aware of. For android files app we use weblogin flow for initial login. If an already existing account is failing, it will also fail back to weblogin.

**Comment by rullzer** [comment]
> Could not resolve OC\Core\Controller\ClientFlowLoginController! Class OCA\OAuth2\Db\ClientMapper does not exist

That sounds very fishy.
Can you restart your php and webserver. Maybe your caching did bad things.

**Comment by styx-tdo** [comment]
hi,
sorry, it was my stupidity.
apparently, cleaning up and removing app/oauth2  is _not_ a good idea...
