### ISSUE TITLE
2FA not working for admin account

### ISSUE THREAD

**Issue by dartmann** [nextcloud/twofactor_totp#342]
**Nextcloud version**: 14.0.4.2
**Operating system and version**: Ubuntu 18.04.1 LTS
**Apache version**: Apache/2.4.29
**PHP version**: 7.2.10

**The issue you are facing**: 2FA is not working for my Nextcloud admin account. 2FA for normal users works as expected. When enabling the feature it does not show any error but after logging out my admin account and logging back in, I am not asked for a TOTP code.
I already tried to solve the issue by removing the 2FA app, but without success.

**Is this the first time you’ve seen this error?**: I can not see any error message.

**Steps to replicate it**: I can not provide steps to replicate, because I think its a local problem (many out there are surely using 2FA for their admin account).

**The output of your Nextcloud log in Admin > Logging**: nothing provided there.

**The output of your config.php file**:

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "keller2",
            "192.168.178.64",
            "keller2.8pzkpdxsetbyyr3f.myfritz.net",
            "keller2.fritz.box",
            "h6h93vrweb7nz2vb.myfritz.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/keller2\/nextcloud",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "integrity.check.disabled": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**The output of your Apache/system log in /var/log/____**: nothing to post

**Comment by ChristophWurst** [comment]
Done :wink: 

Please try to use the CLI to "enable" 2FA. https://docs.nextcloud.com/server/14/admin_manual/configuration_server/occ_command.html?highlight=occ#two-factor-authentication. I think you "disabled" it at some point. Note that this is a legacy feature, removed in Nextcloud 15.

**Comment by dartmann** [comment]
Yep, you're right. Enabling the feature explicitely for my admin account solved this issue. Thank you very much. One last question: why is this feature removed in upcoming NC 15?

**Comment by ChristophWurst** [comment]
Clarification: you didn't enable it, but you un-disabled it.

^ this is the reason why I changed that. It was just too confusing. Admins can still disable providers for a specific user now, but only if the provider supports this. Before, we just overruled the decision "does this user use 2fa?". Now we keep this state persisted for enhanced performance and security.
