### ISSUE TITLE
Allow renaming for app passwords

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/twofactor_totp#345]
### Feature Request

Add the ability to rename apps after adding them and their associated password.

#### Summary

Right now I have added a bunch of devices/apps and passwords so that various apps can use 2FA. However, I didn't spend much effort with naming originally and now my names are not clear as to which device/app the entry is for. For example, I have two with names similar to "NC Bookmark Android App" for the Bookmark app. One is for my tablet and the other for my phone, but it's unclear which is which because I didn't put tablet or phone in the title. I could delete both, make new ones with better names, get new passwords, update my password managers with the new passwords, and then update each device. However, this is a bit of a pain, which is why the rename feature would be nice.

Meanwhile, it might be good to add an "are you sure" dialog when revoking access. Not sure if most people would want that or not.

**Comment by ChristophWurst** [comment]
Do you mean app passwords?

**Comment by koreywithak** [comment]
Yes, sorry. I will edit the original post to clarify.

**Comment by ChristophWurst** [comment]
Got it. This is a dup of https://github.com/nextcloud/server/issues/6717.
