### ISSUE TITLE
The release package became huge from release 1.5.0

### ISSUE THREAD

**Issue by DriverXX** [nextcloud/twofactor_totp#346]
From v1.5.0 the release package grew from 1.5MiB to 14MiB.
I found that this is almost entirely due to a font in "vendor/endroid/qr-code/assets/" named "noto_sans.otf"
Is it really necessary to have this huge font?
Even if this will be used and served to client, serving such a huge file over a network could slow down a lot the page loading.

**Comment by My1** [comment]
Frankly I dont think we need a specific font here. cant we just use whatever font NC is already using? which in the best case (I have no Idea what they have set) could mean the user system would decide on the font

**Comment by ChristophWurst** [comment]
The qr code doesn't even have any font, so this is clearly useless.

Thank you for your feedback. I will try to address this shortly. If anybody is interested in contributing a fix, it's as simple as adding a new ignore entry to https://github.com/nextcloud/twofactor_totp/blob/a479e3883bbf9172eb5576b7867f03c3722ce146/krankerl.toml#L24.

Cheers

**Comment by My1** [comment]
@ChristophWurst done in #355
