### ISSUE TITLE
Could not verify your key. Please try again.

### ISSUE THREAD

**Issue by stephenmoloney** [nextcloud/twofactor_totp#361]
### Steps to reproduce

1. Enable TOTP`

2. Scan QR Code

3. Enter authentication code

### Expected behaviour

No error message, TOTP activated.

### Actual behaviour

get error message

```
Could not verify your key. Please try again.
```

TOTP cannot be activated

Probably the same issue as https://github.com/nextcloud/twofactor_totp/issues/177 but unfortunately that issue does not state a stepwise approach to solving it.

The clock for the server and phone are the same. ```date```` run on the server gives the same time.

**Comment by ChristophWurst** [comment]
Did you check your nextcloud.log (found in your data directory) for any logged errors?

What version of Nextcloud do you use? What version of this app do you use? How did you install it?

**Comment by stephenmoloney** [comment]
Ok, there was some issue with my phone not getting the time correctly from the network. A manual override to the current time did it. This lib is not at fault but rather incorrect time on my phone.

**Comment by facb69** [comment]
I was strugling with this error "Could not verify your key. Please try again." for months.
My phone were merely 3 seconds behind my server but I couldn't have TOTP activated using Google Authenticator.
Based on a comment by  Deff (mddeff) on topic #135 I installed [FreeOTP](https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp) and then it worked like a charm.

**Comment by ChristophWurst** [comment]
> I installed [FreeOTP](https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp) and then it worked like a charm.

But mind the app is kind of dead, it's not updated anymore.

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/stable/user_manual/en/user_2fa.html#using-client-applications-with-two-factor-authentication

**Comment by flavienbwk** [comment]
> Ok, there was some issue with my phone not getting the time correctly from the network. A manual override to the current time did it. This lib is not at fault but rather incorrect time on my phone.

Error was server time for me too. Thank you for pointing out to this error.
