### ISSUE TITLE
Not asked for totp when using user_saml 

### ISSUE THREAD

**Issue by ChessSpider** [nextcloud/twofactor_totp#373]
### Steps to reproduce
1. Configure nextcloud to use https://github.com/nextcloud/user_saml
2. Configure totp for your user
3. Login using SAML

### Expected behaviour
After authentication using SAML, I would expect to the 2nd factor authentication to kick in. Aka, it should ask for the totp code.

### Actual behaviour
Immediately logged in without asking for totp code

### Server configuration

**Operating system**: linux
**Web server:** docker
**Database:** postgresql docker
**PHP version:** 7.2.19

**Version:** 15.0.10

**Updated from an older version or fresh install:**  update

**List of activated apps:**
notable user_saml for login, and twofactor_totp for 2nd factor auth

#### Client configuration
**Browser:**  firefox

**Operating system:** win10

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
nothing of totp or user_saml here

**Comment by ChristophWurst** [comment]
Hi,

could you please post the output of ``occ twofactorauth:state <uid>``?

**Comment by ChristophWurst** [comment]
From IRC

> @ChristophWurst: @schiessle: have you ever used 2fa with saml?
> @schiessle: @ChristophWurst: no, I also think that this is not possible. With saml the authentication happens at the idp not at Nextcloud, the idp redirect the user to an endpoint of the saml app, we check the idp data and log the user in. The whole idea of SSO is that you don't have to authenticate at each service but in one central idp and then you are logged in everywhere
> @ChristophWurst: okay, thanks for that info!
> @schiessle: 2fa should be done at the idp, not at Nextcloud if you use sso

**Comment by ChessSpider** [comment]
Thanks for the feedback. 

Schiessle's opinion, while valid of course, differs from other applications we use (most notably gitlab) and my expectations. I would very much after enabling totp have totp ask for the 2nd factor after being authenticated by the idp if possible. 

(Background: SSO in my setup only asks for username/password w/ long session lifetime, and I prefer to have a separate totp code per (critical) application to prevent abuse of the long-running sessions at the sso-point)

**Comment by ChessSpider** [comment]
Done. I'll close this topic for now, discussion could continue in https://github.com/nextcloud/user_saml/issues/288 
Thanks Christophfor your quick response!

**Comment by ChristophWurst** [comment]
Thank you!
