### ISSUE TITLE
Disabling should require confirmation

### ISSUE THREAD

**Issue by jas4711** [nextcloud/twofactor_totp#38]
Now it is easy to disable TOTP by mistake -- would it be possible to make the user confirm this?  Right now disabling two-factor requires you to re-enable it and scan a new QR code, and if you have loaded it on many devices, this can easily be cumbersome.  Other service providers appear to require confirmation before allowing disabling of two-factor authentication.

I suggest asking for an OTP or the main password to disable the plugin.

**Comment by rogersia** [comment]
+1 for this.

Also a notification that the QR Code will disappear once 2FA is enabled and you reload your user account screen.

**Comment by My1** [comment]
@rogersia well for the notification, that wont be an issue once #22 is taken care of.
