### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by under-score** [nextcloud/twofactor_totp#401]
It has been discussed before but I need an exception of 2F verification for the Webdav endpoints.

**Comment by ChristophWurst** [comment]
This is not how 2FA works, as discussed before.

**Comment by under-score** [comment]
Or teach nextcloud.com/install/#install-clients how to connect. Otherwise you stay alone with any 2F verification. Nextcloud server has  6,273 stars and 2F 38 stars which says it all.

**Comment by ChristophWurst** [comment]
If you use an up-to-date version of any official client it will let you log in via a web view, hence 2FA is seamlessly integrated.

> Nextcloud server has 6,273 stars and 2F 38 stars which says it all.

What's that supposed to mean?

**Comment by under-score** [comment]
> If you use an up-to-date version of any official client it will let you log in via a web view, hence 2FA is seamlessly integrated.

Not for Webdav which is integral for syncing notes, dates and tasks.

> What's that supposed to mean?

It is not getting the attention that it deserves.

**Comment by ChristophWurst** [comment]
I guess you want to use app passwords https://docs.nextcloud.com/server/15/user_manual/session_management.html ...

Anyway, please contact https://help.nextcloud.com/ for support.

**Comment by under-score** [comment]
tried it but give up now as this is not really feasible for numerous clients
