### ISSUE TITLE
Theming: Submit button

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/twofactor_totp#409]
Nextcloud 15.0.2
TOTP 2.1.0

The submit button from TOTP should be grey, like the login button.

![image](https://user-images.githubusercontent.com/16019165/51168445-916ead00-18a9-11e9-90e6-e1591bf5a99c.png)

![image](https://user-images.githubusercontent.com/16019165/51168402-72701b00-18a9-11e9-8cd9-f1b952566eac.png)

**Comment by ChristophWurst** [comment]
Fixed with https://github.com/nextcloud/server/pull/14329

![bildschirmfoto von 2019-03-07 09-51-58](https://user-images.githubusercontent.com/1374172/53944049-d56a7b00-40be-11e9-84bb-8b3d0a74d4b7.png)
^ tested and works

**Comment by ChristophWurst** [comment]
Fixed with https://github.com/nextcloud/server/pull/14329

![bildschirmfoto von 2019-03-07 09-51-58](https://user-images.githubusercontent.com/1374172/53944049-d56a7b00-40be-11e9-84bb-8b3d0a74d4b7.png)
^ tested and works
