### ISSUE TITLE
TOTP TwoFactor not accepting numeric codes

### ISSUE THREAD

**Issue by jedunbar** [nextcloud/twofactor_totp#43]
Hi, Christoph.

I am having trouble with the Google Authenticator codes working with the TOTP plugin in my 9.1 Community Edition environment. Upon logging in, it asks me to provide the numeric code. I open the Google Auth app on my phone, generate a code and enter it. The TOTP login interface rejects it saying that "an error has occurred." I've tried three or four codes at a time and get the same message. I've never successfully two-factored into ownCloud with this plugin. Any idea what could be causing that?

Thanks,

-Josh

**Comment by ChristophWurst** [comment]
Hi @jedunbar,

please check if your phone and server clocks are out of sync. TOTP codes are time-based, hence a time drift might be the reason why the server does not accept your codes. At the moment the app allows a time-drift of three minutes, see https://github.com/ChristophWurst/twofactor_totp/blob/8eca1cc845375a367f791ac65d14de793fe44547/lib/Service/Totp.php#L93

**Comment by jpbaril** [comment]
Same problem here.
Tried to generate code with Authy and OTP Authenticator.
How can I check if my phone and server clocks are out of sync?

**Comment by ChristophWurst** [comment]
> Had same problem.
> There was indeed a 2 minute difference between the two.

So was it fixed after you synced your clocks? Can we close this issue then?

**Comment by jedunbar** [comment]
@ChristophWurst I've not had a chance to test the time drift issue, yet. I did notice that time was off by about 5 minutes between my phone and local server time, though. I went ahead and updated against NTP pool servers. I should be able to test the 2FA plugin later this week. Please leave this issue open for the time being.

Thanks!

**Comment by jlmx13** [comment]
Nextcloud 10.0 (stable) running on a Raspberry Pi 3 with time zone set to UTC, (habit when setting up servers to set time zone to UTC) which is not the time zone I am in, nor the time zone my iPhone is set to. 
Installed and enabled TOTP plugin. Using Lastpass Authenticator on iPhone 6 to generate codes. 
Logging into Nextcloud on PC I receive the same results as OP. Set time zone on the Pi to the same timezone as the iPhone running authenticator resulted in successful login using generated code. 
This makes perfect sense to me (in hindsight) as the codes are time sensitive and my Nextcloud is 4 or 5 hours behind. 
Thank you for this add-in! and just to confirm syncing the time fixed this issue for me, and it works great with Lastpass authenticator.

**Comment by ChristophWurst** [comment]
> Please leave this issue open for the time being.

I assume your problem was solved already 😉
