### ISSUE TITLE
Add OTP Auth to the list of authenticator apps

### ISSUE THREAD

**Issue by grimneko** [nextcloud/twofactor_totp#496]
### Feature Request

Add another TOTP app for iOS/Safari to the list in the readme.md

#### Summary

Since there is only one iOS app I want to suggest adding OTP Auth to the list, which is for free though the author certainly appriciate if you do the in-App purchase to support him :). It comes with FaceID/TouchID support, optional sync across your devices with iCloud, a safari extension for the desktop, entries can be backuped encrypted (AES-256) externally and more. On top its advertisment free, even without the in-App purchase.

Homepage: https://cooperrs.de/otpauth.html
App Store: https://itunes.apple.com/us/app/otp-auth/id659877384?mt=8&uo=4

**Comment by ChristophWurst** [comment]
Sure! Just submit a pull request with a patch that adds it to the list and I'll happily merge that ;)

**Comment by atm0915** [comment]
I created a pull request #514

**Comment by atm0915** [comment]
I had to create a new pull request, #515
