### ISSUE TITLE
Whitelist/Skip by ip address

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/twofactor_totp#534]
It would be nice if 2FA/TOTP could be skipped(whitelisted) for some IPs/range.
In a company, when connections are coming from some IPs ( intranet for example ), the user should not be required to use OTP if the administrator thinks it is not necessary.

There are previously requests at https://github.com/nextcloud/server/issues/2035, but this looks like an app request and not a server request.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/2035 is the ticket this feature request belongs to.
