### ISSUE TITLE
Nextcloud 16

### ISSUE THREAD

**Issue by colirv** [nextcloud/twofactor_totp#551]
### Steps to reproduce
1.Install and enable two factor totp
2.Navigate to settings/user/security
3.Look at Two-Factor Authentication

### Expected behaviour
Should see new TOTP secret, QR code and generate backup codes

### Actual behaviour
Only see generate backup codes

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Version:** (see admin page)  16.0.0

**Updated from an older version or fresh install:**  update from 15

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by tessus** [comment]
No, this is working as designed. As soon as 2fa has been setup, there's no way to retrieve the secret or see the QR code again.

**Comment by ChristophWurst** [comment]
Starting with *Server configuration* you ignored the issue template. Please fill it out.

**Comment by colirv** [comment]
My apologies. tessus was right. I uninstalled it, reinstalled and enabled it and the QR code appeared. Now working fine. Thank you!
