### ISSUE TITLE
Wrong themed button

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/twofactor_totp#559]
- enable theming app
- set it to a diferent color
- click on totp during login
- see wrong colored button

![image](https://user-images.githubusercontent.com/5836855/57520222-6824d180-731d-11e9-8bec-eaf39ab08e30.png)

- NC 16.0.0

**Comment by tobiasKaminsky** [comment]
Hm.
Duplicate of https://github.com/nextcloud/twofactor_totp/issues/409, but why is not yet in?

**Comment by ChristophWurst** [comment]
It *should* be fixed with https://github.com/nextcloud/server/pull/14329. @juliushaertl?

**Comment by tobiasKaminsky** [comment]
I know, but even with 16.0.1 RC1 it is not…

**Comment by juliushaertl** [comment]
Hm, seems my fix is false and just triggered for bright colors. I'll look into, let's reopen https://github.com/nextcloud/server/issues/14317
