### ISSUE TITLE
App not usable

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/twofactor_totp#567]
### Steps to reproduce
1. install and enable app
2. go into user security settings
3. enable TOTP
4. scan QR Code
5. use code

### Expected behaviour
TOTP works

### Actual behaviour
After scan QR Code i got the keys (FreeOTP App). I test the Key, and i got the Message: Your key could not be tested. Please try again

![2019-05-19 18_12_14-Window](https://user-images.githubusercontent.com/21257329/57984956-33bdbd80-7a61-11e9-8611-09eb44a7a8e1.png)

![2019-05-19 18_00_03-Window](https://user-images.githubusercontent.com/21257329/57984929-d164bd00-7a60-11e9-97fa-04f55e681d9f.png)

### Server configuration

**Operating system**: Univention Corporate Server

**Web server:** Apache2

**Database:** PostgreSQL

**PHP version:** 7.2.15

**Version:** 15.0.7.0 (see admin page)

**Updated from an older version or fresh install:** Update from 14.0.x.0

**List of activated apps:** 
 Accessibility
Activity
AppOrder
Audio Player
Auditing / Logging
Bookmarks
Brute-force settings
Calendar
Camera RAW Previews
Collaborative tags
Comments
Contacts
Custom CSS
Deck
Default encryption module
Deleted files
DICOM Viewer
Draw.io
External storage support
Federation
File sharing
First run wizard
Flow Upload
Gallery
GpxEdit
GpxMotion
LDAP user and group backend
Link editor
Log Reader
Mail
Markdown Editor
Mind Map
Monitoring
Nextcloud announcements
Notifications
ONLYOFFICE
Password policy
PDF viewer
Phone Sync
PhoneTrack
Radio
Right click
Share by mail
Support
Talk
Tasks
Text editor
Theming
Two-Factor TOTP Provider
Usage survey
Versions
Video player
Update notification 

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
    1 => '',
  ),
  'datadirectory' => '/var/lib/univention-appcenter/apps/nextcloud/data/nextcloud-data',
  'overwrite.cli.url' => '',
  'dbtype' => 'pgsql',
  'version' => '15.0.6.1',
  'dbname' => '',
  'dbhost' => '',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'instanceid' => '',
  'updatechecker' => 'false',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'overwriteprotocol' => 'https',
  'overwritewbroot' => '/nextcloud',
  'htaccess.RewriteBase' => '/nextcloud',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'filelocking.enabled' => true,
  'trusted_proxies' => 
  array (
    0 => '',
  ),
  'loglevel' => 2,
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_smtphost' => '',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_from_address' => 'noreply',
  'mail_domain' => '',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'mail_smtpport' => '',
  'mail_smtpsecure' => 'tls',
  'theme' => '',
);
```

#### Client configuration
**Browser:** Firefox or Chrome

**Operating system:** Windows 10

##### Web server error log
```
No entrys in Logs
```

**Comment by ChristophWurst** [comment]
Sounds like your phone and server clocks are out of sync.

**Comment by corincorvus** [comment]
ah the server was unsync...
Now it works!
Thanks :)

**Comment by corincorvus** [comment]
ah the server was unsync...
Now it works!
Thanks :)
