### ISSUE TITLE
add a PIN option or use the NC password as PIN together with TOTP-Code

### ISSUE THREAD

**Issue by cyberbix** [nextcloud/twofactor_totp#594]
### Feature Request

Wouldn´t it be nice to use the NC password as PIN together with the TOTP code to streamline the login to a one-step procedure instead of having two-step ?

#### Summary

TOTP-Seeds are not secure by default. The Seed can be copied or can be stolen. Together with a short pin, in front of or added after the TOTP-Code from the generator.

Of course NC delivers with the password dialog first and the TOTP-Provider dialog in the second stage this behaviour at most, but having a single stage process would be nice !

**Comment by ChristophWurst** [comment]
I don't think we want to support that. Have you seen the other factors we support? Sounds like you might like that we also do `u2f` as second factor.

**Comment by cyberbix** [comment]
No. I don´t mean using a hw device for the 2nd Auth, I thought of streamlining the TOTP-Auth into a a one-step procedure, as it would work when I integrate an external OTP-Provider through LDAP, etc.

But I understand that this would change the hole login process.

**Comment by ChristophWurst** [comment]
Yeah I do get that. But it's indeed not now how our 2FA works as it's capable of supporting a much more complex set of providers.

**Comment by cyberbix** [comment]
I tested the U2F 2FA App now to get exactly what your meaning. But event there - first of all the password has to entered. Especially when using an U2F HW device - entering the password can be annoying...

I still think there could be an option to disable the "Password" provider when enforcing 2FA for all users, so in the login dialog just a user field is displayed and after hitting enter one of the 2FA providers is presented. Even enrolling new users with the twofactoradmin option and a 48h one time key would be possible.

But if no one else ever claimed about the additional pw when using 2FA my request maybe irrelevant ;-)

Thanks anyway for getting back !

**Comment by ChristophWurst** [comment]
Yes, I think this has been discussed before. The problem with showing a provider right a way is that it only work flawlessly with a single one. If you show any other right after the password input you'd first have to solve the problem that which provider to pick (most recently one? most often used one?) and then many providers have side effects. Showing their challenge page sends out messages or changes database data. It's not safe to show them.

**Comment by cyberbix** [comment]
Of course, before you don´t have the userid, you cannot show any auth-methods. There could go the idea of first entering the username and then showing a list of possible auth providers. Maybe there could be an administrative setting like "two-step login process". This setting does not makes too much sense if just the "plain password" auth provider is available for a user. But if there are other auth providers available for a user, especially 2FA´s, it makes more sense. The user selects the auth provider of this choice and THEN the respective dialog is displayed.

So if the admin of a Nextcloud instance would like to disable plain password login at all and i.e. just would like to allow through U2F, he can "disable" the plain password provider and on the login page there´s just a username field displayed. After entering a respective username, the U2F auth provider and i.e. the admin OTP auth options, ore TOTP are displayed, the user selects the U2F and in the following dialog U2F or TOTP comes in place. For U2F i.e. there could be an additional field for the U2F PIN (what does not work at the moment with a Yubico U2F hw token btw).

For TOTP i.e. the typical TOTP dialog would be displayed and if pssobile availabe in the future from the TOTP-provider , the user must  enter PIN+TOTP-code, TOTP-code + PIN, however...

Just an idea, I understand that the hole auth model probably has to be redesigned. But together with an administrative setting that allows the "legacy" model, experience for admins that want to keep the good old static pw auth model it would be seamless..
