### ISSUE TITLE
TOTP does not keep the chosen theme color

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/twofactor_totp#664]
TOTP does not keep the chosen theme color, in the specific button.
I chose a border color in the theme nextcloud but then when 
I have to immerse the totp I see that it keeps the blue color. 
Can you make him take the theme color that you consider?

I attach screenshots to make you understand

![Immagine](https://user-images.githubusercontent.com/35575744/63915206-b62d2480-ca35-11e9-9451-25ebedcbabb7.png)

button blue color does not maintain the burgundy color

![Immagine2](https://user-images.githubusercontent.com/35575744/63915212-baf1d880-ca35-11e9-95bf-a1cbf927adf3.png)

**Comment by ChristophWurst** [comment]
This is known and tracked in https://github.com/nextcloud/server/issues/14317. Closing as duplicate. Thanks for the feedback!
