### ISSUE TITLE
Add Option "Remember on this computer"

### ISSUE THREAD

**Issue by laurentdinclaux** [nextcloud/twofactor_totp#68]
Add the option "Remember on this computer" to allow the TwoFactor auth to be used only once per browser, for example.

**Comment by ChristophWurst** [comment]
The classic remember-me functionality should be enough, right? It's currently broken unfortunately (it was me, sorry 🙊), but good news: I'm about to finish the bug fix in https://github.com/nextcloud/server/pull/1347.

**Comment by ChristophWurst** [comment]
Hello,
remember-me was fixed for NC11, which will be released soon.

**Comment by My1** [comment]
it doesnt seem to be in beta2. will it come later on the run to NC11?

**Comment by ChristophWurst** [comment]
The general fix is in beta1, but there were two minor bugs that are fixed in beta2
https://github.com/nextcloud/server/pull/2353
https://github.com/nextcloud/server/pull/2351

**Comment by ChristophWurst** [comment]
> it doesnt seem to be in beta2. will it come later on the run to NC11?

What doesn't work?

**Comment by ChristophWurst** [comment]
Please fie an issue in the server repo if you are having problems with remember-me. Thanks

**Comment by My1** [comment]
I dont see any option to remember the PC.

**Comment by ChristophWurst** [comment]
Then you enabled a app that disables it, e.g. external storages.

**Comment by My1** [comment]
lol, I dont even remember turning it on yet, but there should be an info that it disables remember login, but it's sad that it disables that.

**Comment by My1** [comment]
but one thing that would be epic would be the option to only remember the 2nd factor, meaning that it doesnt remember the whole session but still asks for User/PW without asking for the 2nd factor in trusted computers (actually a pretty common practice in the web as far as I see it)
