### ISSUE TITLE
I'm an idiot… Enabled 2FA and locked myself out…

### ISSUE THREAD

**Issue by SteveBobBob** [nextcloud/twofactor_totp#692]
I enabled and enforced 2FA but didn't configure users…

Now when I try to log in with my admin account I cannot because 2FA wasn't configured…

How can I bypass the 2FA to regain access to my nextcloud to configure 2FA properly?

Thanks

**Comment by ChristophWurst** [comment]
On the CLI you can run `occ twofactorauth:enforce --off`

https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html

**Comment by jospoortvliet** [comment]
Please, in the future, don't ask questions like this on github. This is what help.nextcloud.com is for.

**Comment by SteveBobBob** [comment]
Apologies… Will ask there when and if I encounter any future issues.

Thank you.
