### ISSUE TITLE
LDAP user in excluded local group is still prompted for a TOTP code

### ISSUE THREAD

**Issue by scluff** [nextcloud/twofactor_totp#715]
I am not sure if this a twofactor_totp or server issue.

I have 2FA enforcement turned on, and am exclusively using the TOTP provider. LDAP/AD integration is enabled (only users, not LDAP/AD groups). I have a local group which is excluded from 2FA enforcement. If I add an LDAP/AD user to this local group, they are still prompted for a TOTP code on login. If I create a local user, and add them to the same group, they are not prompted to set up or use a TOTP code.

**Comment by ChristophWurst** [comment]
so? was it resolved?

**Comment by scluff** [comment]
Yes, misunderstanding on my part. Adding a 2FA enrolled user to an excluded group does nothing, 2FA needs to be turned off for the user with occ twofactorauth:disable.
