### ISSUE TITLE
User lost authenticator and backup codes

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/twofactor_totp#755]
Hi,

a friend and user of my private cloud with TOTP damaged his phone. So he needed to repair and reset his device. He lost his backup codes too.

how i can send him backup codes for TOTP on his Account?
he cant login.

Best Regards

**Comment by ChristophWurst** [comment]
Hi,

please see https://help.nextcloud.com/c/support for community support.

https://apps.nextcloud.com/apps/twofactor_admin might help. Otherwise check the documentation for how to disable providers via the CLI.

Cheers
