### ISSUE TITLE
Tested with the following apps

### ISSUE THREAD

**Issue by beerisgood** [nextcloud/twofactor_totp#760]
You can add the app [andOTP](https://github.com/andOTP/andOTP) to the "Tested with the following apps" list which works too.

This nice app is also available in F-Droid: https://f-droid.org/packages/org.shadowice.flocke.andotp/

**Comment by ChristophWurst** [comment]
Hi :beer:,

please submit this as pull request and we can add it to the list :)

Thanks for testing and providing the feedback!

Cheers

**Comment by beerisgood** [comment]
https://github.com/nextcloud/twofactor_totp/pull/775
