### ISSUE TITLE
Exclude IP ranges

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/twofactor_totp#762]
### Feature Request
It would be nice if I could exclude certain IP ranges from TOTP, e.g. my local home network, but traffic from the Internet or VPN still needs TOTP.

#### Summary

Exclude specific IP ranges from TOTP authentication by mark them as trusted.

**Comment by ChristophWurst** [comment]
Duplicate of #141 

See https://github.com/nextcloud/server/issues/2035

**Comment by Somebodyisnobody** [comment]
It's a server-issue?!

**Comment by ChristophWurst** [comment]
yes?!
