### ISSUE TITLE
TOTP TwoFactor not working with Carddav/CalDav on MacOs

### ISSUE THREAD

**Issue by sipfli** [nextcloud/twofactor_totp#78]
It's not possible to sync Calendar and Contacts if the TOTP TwoFactor is activated. The Connection can't be established from the MacOS. How this can be done with TOTP activated ?

**Comment by ChristophWurst** [comment]
You need to generate device passwords in your personal settings. See https://docs.nextcloud.com/server/11/user_manual/session_management.html#managing-devices. Please let me know if you have any further questions.

**Comment by sipfli** [comment]
Works fine, thanks.
