### ISSUE TITLE
Expired code entry still allows access.

### ISSUE THREAD

**Issue by defaultuser8** [nextcloud/twofactor_totp#780]
### Steps to reproduce
1. Enter username and password.
2. Enter code that expires before pressing enter.
3.Nextcloud reports "Access forbidden CSRF check failed"
4. Pressing back button on browser gains access to nextcloud account.

### Expected behaviour
You should not gain access to your account.

**Comment by ChristophWurst** [comment]
If you get to a CSRF page the code was never used as the check is performed very early before the actual operation is executed.

So, this is fine.

The CSRF check failing is the issue. But I'm confident this is caused by misconfiguration. Something's not right with your session settings.
