### ISSUE TITLE
[SOLVED] OC 9.1.2, not asking for 2nd factor

### ISSUE THREAD

**Issue by victorbw** [nextcloud/twofactor_totp#79]
unfortunately I have absolutely nothing in my logs to show, its simply not working like it wasnt there at all.

activation via manual upload (SCP) and generating TOTP works so far.

Is there already a fix ongoing/planned?

**Comment by ChristophWurst** [comment]
Hi,

could you please post steps to reproduce this problem? Are you using the app with ownCloud?

**Comment by ChristophWurst** [comment]
How did you install the app?

**Comment by victorbw** [comment]
Sure:

1. Installed ownCloud 9.1.2 via tarbal (PHP 7, MySQL 5.4, APACHE 2, Redis-Cache)
2. downloaded 2FA-App via [https://apps.owncloud.com/content/show.php/TOTP+TwoFactor+%28Google+Authenticator%29?content=174726](url) and unpacked it to disk
3. uploaded wia SCP
4. chowned
5. activated via WebUI (for everyone, because its only a lab)
6. existing ownCloud user activated app (from internal database, non-ldap) and got TOTP (google authenticator)
7. log in with password
8. no 2nd authentication seen, came directly to files-UI

note: was first unable to directly activate/install TOTP via admin-app-ui, response 400 (seems to be missing).

**Comment by ChristophWurst** [comment]
Did you enable TOTP in your personal settings? E.g. generate and scan the QR code?

**Comment by victorbw** [comment]
yes I did.

Did I do something wrong?

**Comment by ChristophWurst** [comment]
> existing ownCloud user activated app (from internal database, non-ldap) and got TOTP (google authenticator)

What do you mean by that?

> yes I did.
> 
> Did I do something wrong?

Not sure yet 😉

**Comment by ChristophWurst** [comment]
Btw. there were unfortunately many other users complaining that TOTP 2FA suddenly stopped working with their ownCloud installation, although the app was not changed. Upgrading to Nextcloud fixed it apparently.

**Comment by victorbw** [comment]
is there any chance to have a fix for ownCloud as well?

**Comment by victorbw** [comment]
> Not sure yet :wink:
lol, you made my day :smile: 

> What do you mean by that?
the owncloud-user, which means its an internal-ownCloud-user (non-ldap or any external database) was created before the app was installed and activated.

der Herr grüsst :wink:

**Comment by ChristophWurst** [comment]
still, what do you mean by step 6? I don't see the step where you scanned the QR code.

**Comment by victorbw** [comment]
> existing ownCloud user activated app (from internal database, non-ldap) and got TOTP (google authenticator)

got TOTP means: yes, I've scanned it.

**Comment by ChristophWurst** [comment]
Hmm. Could not reproduce it with a fresh install :-|

**Comment by victorbw** [comment]
strange, other users mentioned the same issue, didnt they?

**Comment by ChristophWurst** [comment]
No, apparently it was another one.

Do you have access to your DB? If so, please check if you're facing the same problem as described here https://github.com/nextcloud/twofactor_totp/issues/56#issuecomment-245289303.

I'm curious whether that value is present in your DB too.

**Comment by victorbw** [comment]
indeed, there's this entry there. 

and after i've manually manipulated it to **'two_factor_auth_enabled','1'** it worked again.

thank you for your help!

**Comment by ChristophWurst** [comment]
@victorbw strange. did you run the occ command before to disable 2FA?

**Comment by victorbw** [comment]
not as far as i can remember, but so i guess i've ran it once to check if it really works.

probably the (re)activation of that app didnt set the value then. because i've checked it twice if the web-ui activation of the app would set the value, but unfortunately it didnt.

**Comment by ChristophWurst** [comment]
> probably the (re)activation of that app didnt set the value then. because i've checked it twice if the web-ui activation of the app would set the value, but unfortunately it didnt.

The value should not be touched unless the occ commands are run

**Comment by victorbw** [comment]
probably there's a missunderstanding in setting that value via web-ui, in which most users expect that the value would be set then.

was that mentioned in the owncloud/nextcloud-manual?

**Comment by ChristophWurst** [comment]
Those are two different settings. The one on the web-ui enables/disables *one specific 2FA provider*, whereas the occ command enables/disables 2FA for a given user generally. The occ is only meant for temporary disabling the 2FA in case a use lost their second factor. This is documented on https://docs.nextcloud.com/
