### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by son1c** [nextcloud/twofactor_totp#80]
Hi,

i get this message when i try to download it:

Client error response [url] https://github.com/nextcloud/twofactor_totp/releases/download/0.4.1/twofactor_totp_owncloud.tar.gz [status code] 404 [reason phrase] Not Found

**Comment by ChristophWurst** [comment]
You can download the app either here https://apps.nextcloud.com/apps/twofactor_totp or here https://github.com/nextcloud/twofactor_totp/releases
