### ISSUE TITLE
Can't see checkbox "Enable TOTP" in Personal Settings

### ISSUE THREAD

**Issue by ltdaydo** [nextcloud/twofactor_totp#804]
Hi Everyone
I'm install and Enable "Two-Factor TOTP Provider" ver 4.1.2 success, but in Setting -> Security of Personal do not show checkbok "Enable TOTP"
Anyone have suggesstion for me
![image](https://user-images.githubusercontent.com/59592342/72504184-e43dc480-386f-11ea-88cd-1d35412508a9.png)

Thanks so much

I'm install newest version of Nextcloud (17.0.2) on CentOS 8

**Comment by ChristophWurst** [comment]
Hello :wave: 

Looks like a js error to me. Please open the browser console and reload the page. I expect an error to appear. Then post a screenshot of that.

**Comment by ltdaydo** [comment]
Hi @ChristophWurst 
Below is the screenshot of Developper Tools 
![1](https://user-images.githubusercontent.com/59592342/72579674-6085e580-390c-11ea-8d82-ac9cdaab2ded.png)

Many Thanks

**Comment by ltdaydo** [comment]
And this is the Logging in web browser og nextCloud
![a](https://user-images.githubusercontent.com/59592342/72580332-4e0cab80-390e-11ea-9bf0-2ef80a5e71e6.png)

**Comment by ChristophWurst** [comment]
so, guess you didn't install the app via the app, did you?

**Comment by ltdaydo** [comment]
> so, guess you didn't install the app via the app store, did you? the composer dependencies are missing. use an archive from the github releases page, download the app via the app store or install packages with `composer install`

Hi @ChristophWurst 
I'm git clone from github by command:
"git clone https://github.com/nextcloud/files_antivirus"
What does that mean `composer install` ?
Thanks you

**Comment by ltdaydo** [comment]
> so, guess you didn't install the app via the app store, did you? the composer dependencies are missing. use an archive from the github releases page, download the app via the app store or install packages with `composer install`

Thanks for help
I had fixed

**Comment by ChristophWurst** [comment]
Okidoke.

Generally just cloning an app won't work. Use the app store or an release from https://github.com/nextcloud/twofactor_totp/releases. Only for developer setups it makes sense clone and install dependencies manually.
