### ISSUE TITLE
Disabling two factor auth

### ISSUE THREAD

**Issue by Wurzelmann** [nextcloud/twofactor_totp#81]
Hi!

After flashing a new ROM to my mobile phone, I cannot login to my nextcloud anymore... what's the best way to disable 2FA "from the outside"? I have still access to the server of course, but I cannot get past the login screen...

Thanks in advance!

**Comment by LukasReschke** [comment]
The OCC console can help you for that. But generally: help.nextcloud.com is the place to go. This is only for tracking bugs.

```
 ./occ twofactor:disable wurzelmann
```
