### ISSUE TITLE
Error 404 when enabling

### ISSUE THREAD

**Issue by Raindeer44** [nextcloud/twofactor_totp#82]
When trying to enable this app on my new NextCloud 10.0.1 installation, I get the following message:

Client error response [url] https://github.com/nextcloud/twofactor_totp/releases/download/0.4.1/twofactor_totp_owncloud.tar.gz [status code] 404 [reason phrase] Not Found

It looks to me that the targz shouldn't have the "_owncloud" part of the filename; https://github.com/nextcloud/twofactor_totp/releases/download/0.4.1/twofactor_totp.tar.gz works correctly.

**Comment by ChristophWurst** [comment]
Hi @Raindeer44,

you're right, we've recently moved the repo and it seems like the URL changes. Let me fix this.

**Comment by ChristophWurst** [comment]
So. Should work now. @Raindeer44 could you please check and verify? Thanks :-)

**Comment by Raindeer44** [comment]
Well done! I can confirm it works! :)

**Comment by ChristophWurst** [comment]
Thanks :-)
