### ISSUE TITLE
README recommends FreeOTP, which is no longer actively maintained

### ISSUE THREAD

**Issue by sporksmith** [nextcloud/twofactor_totp#824]
The fdroid release is 4 years old.
This issue recommends the fork FreeOTP+ instead: https://github.com/freeotp/freeotp-android/issues/207

**Comment by sporksmith** [comment]
FWIW I've successfully set up 2-factor auth on Nextcloud with FreeOTP+, but I haven't tested it extensively.

**Comment by SuperSandro2000** [comment]
Yeah, you shouldn't recommend software which didn't get any update in 4 years.

**Comment by ChristophWurst** [comment]
Submit a PR please
