### ISSUE TITLE
TOTP required

### ISSUE THREAD

**Issue by yanntech** [nextcloud/twofactor_totp#84]
Hi,

It should be interesting with an admin account to force TOTP usage.
Lambda user can't disable TOTP when defined (only admin can reset totp status).
Next step, on first login start a TOTP enrollment procedure.

Regards,
Yann

**Comment by MariusBluem** [comment]
See: https://github.com/nextcloud/twofactor_totp/pull/74

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/twofactor_totp/issues/41
