### ISSUE TITLE
CAS authentication over Two-Factor TOTP Provider

### ISSUE THREAD

**Issue by labrude91** [nextcloud/twofactor_totp#842]
Hello,

I use Nextcloud 17.0.2, I configured Ldap authentication and CAS authentication ( plugin CAS user and group backend 1.8.1).
I activate Two-Factor TOTP for all users. It works perfectly when my users connect through LDAP, but not with CAS.
In CAS case, the user authenticate and he is directly redirected to it's nextcloud's account.
Have I misconfigured something ?

**Comment by ChristophWurst** [comment]
Answered by https://github.com/felixrupp/user_cas/issues/79#issuecomment-597772138
