### ISSUE TITLE
version information

### ISSUE THREAD

**Issue by My1** [nextcloud/twofactor_totp#87]
My nextcloud tells me upon installing the relase 0.5.0:
"This addon hasnt set a minimum version, this will be treated as error in the future"

**Comment by ChristophWurst** [comment]
Hi,

which version of Nextcloud?

0.5.0 is intended for NC11 only. I quickly set up a NC11 beta installation and didn't get that warning:
![bildschirmfoto von 2016-11-26 13-56-02](https://cloud.githubusercontent.com/assets/1374172/20640527/313369e2-b3e0-11e6-9d60-4fdfa64cba98.png)

**Comment by My1** [comment]
how am I even supposed to know that?
It is literally written nowhere, and the release notes just say "NC 11 support, not that it's NC11 Only"

I am on 10 point something

**Comment by ChristophWurst** [comment]
Okay sorry for the misinformation, I'll update the release description.

0.5 is available via apps.nextcloud.com for NC11+, whereas NC10 and NC9 still use the old oc app store where I won't upload any newer releases.

**Comment by ChristophWurst** [comment]
Updated: https://docs.nextcloud.com/server/11/developer_manual/app/code_signing.html#is-code-signing-mandatory-for-apps

Thanks

**Comment by ChristophWurst** [comment]
> but intrestingly even if I select beta channel I cant update to 11

NC11 is not yet out. See https://nextcloud.com/blog/two-reasons-why-you-should-test-nextcloud-11-beta-this-weekend/ 😉

**Comment by My1** [comment]
on the bottom right of the nc DL page it says 11 beta furthermore it says "2016-11-25" (aka yesterday) as 11 beta release date on the schedule here
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
so it looks like it has been released as far as it looks like

**Comment by My1** [comment]
also why can this even install in 10? u2f cant install and says it needs 11...

**Comment by ChristophWurst** [comment]
> also why can this even install in 10? u2f cant install and says it needs 11...

Good point. I was surprised too that your NC10 installation did not detect the incompatibility. My first guess is that the old meta data markup used 'dependencies' > 'owncloud' whereas now it's 'dependencies' > 'nextcloud'. I've remove the owncloud dependency specification but apparently I should consider adding it back to prevent those installations. I might have to set it to 'owncloud' 'max-version' 1 to prevent people from installing on older releases …

**Comment by My1** [comment]
but then again with everything pointing to the beta being out why doesnt my nc see the 11 beta even though I set it to beta channel. it says that it's up to date.

**Comment by ChristophWurst** [comment]
That's a topic for https://help.nextcloud.com/. I'm not sure if the updater in NC10 will show the beta.

**Comment by My1** [comment]
oh okay didnt know that existed, just threw in a topic:
https://help.nextcloud.com/t/updating-from-10-to-11-beta/5526
