### ISSUE TITLE
Device-specific passwords often get invalidated

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/twofactor_totp#878]
As I'm using TOTP for my user accounts, I'm also using device specific password for things like Thunderbird, Andriod DAVx5, floccus bookmarks sync and of course the desktop client of NextCloud.

Starting a couple of weeks ago, I have to renew the device specific passwords pretty often. For the desktop client e.g. almost daily. The DAVx5 is complaining more often now too. TBH, I have no idea why.

Today I started to investigate and found out that for those that don't work, the value of `password_invalid` in the `authtoken` table is set to 1. I just don't know why this is happening and how I could fix it. I can't even find any code in the app source code which would actually touch that value at all.

Does anyone have a clue what's going on here? Has anyone seen something similar?

**Comment by ChristophWurst** [comment]
Possibly triggered through this path:https://github.com/nextcloud/server/blob/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/lib/private/User/Session.php#L756

I guess your user back-end is just flaky.

In any case please open a proper bug report at https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md by following the issue template.

I highly suspect this is a setup issue.

**Comment by jurgenhaas** [comment]
Thanks @ChristophWurst for the hint, but that's not the correct path. That one deletes the token from the authtoken table, but in my case the field `password_invalid` gets set to 1. If I were able to find where this is happening I could probably trace the root for it.

**Comment by ChristophWurst** [comment]
It does not. It is the path that is taken to invoke `setPasswordInvalid(true)`.

**Comment by jurgenhaas** [comment]
OK, found it. What confused me that the validation works for many hours and then suddenly fails. It looks like that must be in this code:

```
		foreach ($this->backends as $backend) {
			if ($backend->implementsActions(Backend::CHECK_PASSWORD)) {
				$uid = $backend->checkPassword($loginName, $password);
				if ($uid !== false) {
					return $this->getUserObject($uid, $backend);
				}
			}
		}
```

My only backend is the database. Ldap is not enabled, SAML is installed but not configured. And I don't yet understand the code, how this is ever checking auth tokens instead of the user password.

One of the processes regularly failing is a monitoring task which curls into https://cloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json and providing the `Authorization: Basic [base64 encoded username:app-token]` as a header value for authentication.

What can a "flaky back-end" actually be to work for a while for this and then failing?

I'm hosting half a dozen NC instances for many years and all installation and configuration is 100% automated by Ansible. And only recently, the behaviour changed as described.

**Comment by ChristophWurst** [comment]
> I'm hosting half a dozen NC instances for many years and all installation and configuration is 100% automated by Ansible. And only recently, the behaviour changed as described.

Are you a partner? Then please open a new ticket in our support system.

In any other case please open a proper bug report at https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md by following the issue template.

**Comment by jurgenhaas** [comment]
No, I'm not a partner, I'm just hosting for some of my clients. I'll open a new ticket then.
