### ISSUE TITLE
Signature verification error on update

### ISSUE THREAD

**Issue by tribut** [nextcloud/twofactor_totp#90]
Hey,

when trying to update to 0.4.1 on ownCloud 9.1.2, I get the following error:

    - twofactor_totp
    	- EXCEPTION
	    	- OC\IntegrityCheck\Exceptions\InvalidSignatureException
	    	- App Certificate is not valid.

**Comment by ChristophWurst** [comment]
Hi and thank you for your report.
This app is primarily developed, tested, signed, packaged and distributed for Nextcloud now.
There's even a newer version available, v0.5, but for Nextcloud 11 only.
If you would like to use TOTP 2FA in the future I recommend to upgrade to Nextcloud. Other OC users that had problems with this app upgraded too and they all reported that it resolved their issues ;-)
