### ISSUE TITLE
[Nextcloud login page] Skip the first TOTP window

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/twofactor_totp#92]
To make the login more user-friendly, I suggest to skip the page which is shown after the password is accepted, the /login/selectchallenge screen with "Bestätigung in zwei Schritten..." and "Mit einer TOTP-App authentifizieren."

This currently requires an unnecessary(in my view) additional click of the user. I suggest to skip directly to the /challenge/totp page.

Even better would be a hook which allows to enter username, password and TOTP on the very first login screen.

**Comment by ChristophWurst** [comment]
Will come with NC11 https://github.com/nextcloud/server/pull/1169 😉

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/twofactor_totp/issues/69

**Comment by Wikinaut** [comment]
Danke :-))
