### ISSUE TITLE
[Suggestion/Question] TOTP as one-factor login

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/twofactor_totp#94]
I would like to see a way to configure Nextcloud and what is currently called Twofactor_TOTP as **single factor** login.

Is this already in your roadmap, or even possible now ?

**Comment by ChristophWurst** [comment]
> Is this already in your roadmap

No.

> or even possible now

No.

I'm curious, why would you want to do that? Would that even make sense? :-)

**Comment by ChristophWurst** [comment]
You could implement your custom user backend which takes a TOTP code as password 😉

**Comment by Wikinaut** [comment]
@ChristophWurst There's nothing bad on having TOTP-only logins. (It can be implemented with an additional password.) TOTP-password-only is better than a weak-password-only login.

**Comment by ChristophWurst** [comment]
I see, thanks for your clarification. This is out of scope for this app, but could be developed as sepearate Nextcloud app. Let me know if you need some poiters to get started :-)
