### ISSUE TITLE
Add Support for Nextcloud 11

### ISSUE THREAD

**Issue by Hanzei** [nextcloud/twofactor_totp#95]
On Nextcloud 11 the activation fails with:
` App "Two Factor TOTP Provider" cannot be installed because the following dependencies are not fulfilled: Server version 9.2 or lower is required. `

**Comment by ChristophWurst** [comment]
Did you use the latest version? How did you install it?

**Comment by Hanzei** [comment]
I installed via the nextcloud app interface. I'm using version 0.4

**Comment by ChristophWurst** [comment]
Okay. That should not happen. You've updated from an older version of Nextcloud right?

**Comment by ChristophWurst** [comment]
Apparently this is an issue of the Nextcloud server, see https://github.com/nextcloud/server/issues/2403. Basically you have to uninstall and re-enable the app, then it will fetch the latest version from the new app store.
Sorry for the inconvenience :-)

**Comment by Hanzei** [comment]
Thanks for the help .Is there any way to backup the settings?

**Comment by ChristophWurst** [comment]
I did a quick test and uninstalling apparently does *not* remove any data, so your settings are not lost. But, as always, do a backup of your database, just in case something unexpected happens ;-)

**Comment by Wikinaut** [comment]
@ChristophWurst wrote above

> Basically you have to uninstall and re-enable the app, then it will fetch the latest version from the new app store.


I tried this, but deinstallation and trying to reinstalls fails with the same message.

```
Für diese App wurde keine untere Versionsgrenze für Nextcloud gesetzt. Dies wird zukünftig als Fehler behandelt.
Die App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:
Server version 9.2 or lower is required.
```

**Comment by Hanzei** [comment]
@ChristophWurst deinstallation and reinstallation worked out fine. The data didnt got lost

**Comment by ChristophWurst** [comment]
> I tried this, but deinstallation and trying to reinstalls fails with the same message.

Did you use the latest version, 0.5?

**Comment by Wikinaut** [comment]
@ChristophWurst the one, which is offered in the Apps window.
![20161214-12 09 27_auswahl](https://cloud.githubusercontent.com/assets/1151915/21179845/31c3cb76-c1f6-11e6-9866-ca2f13953b0f.png)

**Comment by Wikinaut** [comment]
Reason was: /nextcloud/apps/twofactor_totp had root:root ownerships instead of www-data:www-data.
After fixing the ownership, deinstallation and installation worked fine.
