### ISSUE TITLE
Error 500 (can't find 'enable'?)

### ISSUE THREAD

**Issue by wunair** [nextcloud/twofactor_totp#97]
I've installed NextCloud 10.0.1 and downloaded twofactor_totp 0.4.1. After installing it the option appeared for me to activate TOTP, but as soon as I press the checkbox, I get this error.

![image](https://cloud.githubusercontent.com/assets/11733366/21098607/514cc69c-c06a-11e6-857e-3ccd7989c412.png)

I've checked the map settings in twofactor_totp and the only file in settings is personal.php. Have I done something wrong or have I missed a step here?

**Comment by ChristophWurst** [comment]
Hi!

> downloaded twofactor_totp 0.4.1.

Where did you download the app from?

Please take a look at your nextcloud.log log file. I'm sure something's logged into it whenever that error occurs.

**Comment by wunair** [comment]
Thanks for the quick response. I've downloaded the app from your github page (https://github.com/nextcloud/twofactor_totp/releases).

The logs give me this.

![image](https://cloud.githubusercontent.com/assets/11733366/21098759/022a859e-c06b-11e6-9529-01ed2310c852.png)

**Comment by ChristophWurst** [comment]
I see. So you've downloaded GitHub's zip archive instead of the actual app package. Use 'twofactor_totp.tar.gz' at https://github.com/nextcloud/twofactor_totp/releases/tag/0.4.1 instead. Thanks :-)

**Comment by ChristophWurst** [comment]
dup of #65

**Comment by wunair** [comment]
That seemed to be the issue. Thanks. 

I'm not sure if I should open a new issue for this, but I bumped into a new issue. As I filled in the code for two factor. "An error occured while verifying the token".

Any idea what the issue is?

**Comment by ChristophWurst** [comment]
> Any idea what the issue is?

Compare the clocks of your server and your smartphone. If they differ more than 30secs it can be problematic. If that's not the case please create a new issue and provide some information about your setup and steps to reproduce, thanks :-)

**Comment by wunair** [comment]
After an hour of struggling I found what the issue was. The Google Authenticator app shows 3 numbers, space, 3 numbers. I thought I had to add the space the entire time :')

And the time on the server was also a factor.

**Comment by ChristophWurst** [comment]
Oh, good to know, personally I don't use Google Authenticator :-)

I'll consider adding this to the documentation, once I write one 😉 

Thanks for your feedback!
