### ISSUE TITLE
If enabled causes Smartphone App on Android to show "Wrong Password"

### ISSUE THREAD

**Issue by soydemadrid** [nextcloud/twofactor_totp#98]
Enabling Twofactor TOTP in my web interface causes my mobile/smartphone app to show the error "wrong password".

It would be nice to have this enabled for better web security but still allow the smartphone app access or even better have the app ask for the Google authenticator code etc.

Thanks for any help if I'm not doing this correctly.

**Comment by ChristophWurst** [comment]
Hi,

simply generate an app password for your Android app and it should be fine, see https://github.com/nextcloud/twofactor_totp/issues/55#issuecomment-244766353 :-)

**Comment by soydemadrid** [comment]
Cool as! Works great thanks.
