### ISSUE TITLE
How do I remove totp from deleted users?

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/twofactor_totp#985]
I'm a bit braindead. I've successfully deleted the user in nextcloud, then created a new user with the exact same name. With TOTP forced the new user reuses the old users totp with no option to reset.

How do I fix that? This is with NC 20.0.1.

**Comment by ChristophWurst** [comment]
It's a duplicate of https://github.com/nextcloud/twofactor_totp/issues/384. You're not doing it wrong, this is a know bug.

I haven't had the time to fix this yet. Any help is appreciated.

**Comment by CaixaNegraPT** [comment]
@ChristophWurst is there any way to manually delete the records in the database?
